[package]
name = "ppl_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
lazy_static = "1.4.0"
argh = "0.1.7"
substring = "1.4.5"