use std::fmt::Display;

use crate::{vm::expressions::predefined_functions, Res};

use super::VariableValue;

#[repr(i16)]
#[allow(dead_code)]
#[allow(non_camel_case_types)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub enum FuncOpCode {
    END = 0,
    CPAR = -1,
    UPLUS = -2,
    UMINUS = -3,
    EXP = -4,
    TIMES = -5,
    DIVIDE = -6,
    MOD = -7,
    PLUS = -8,
    MINUS = -9,
    EQ = -10,
    NE = -11,
    LT = -12,
    LE = -13,
    GT = -14,
    GE = -15,
    NOT = -16,
    AND = -17,
    OR = -18,
    OPAR = -19,
    LEN = -20,
    LOWER = -21,
    UPPER = -22,
    MID = -23,
    LEFT = -24,
    RIGHT = -25,
    SPACE = -26,
    FERR = -27,
    CHR = -28,
    ASC = -29,
    INSTR = -30,
    ABORT = -31,
    LTRIM = -32,
    RTRIM = -33,
    TRIM = -34,
    RANDOM = -35,
    DATE = -36,
    TIME = -37,
    U_NAME = -38,
    U_LDATE = -39,
    U_LTIME = -40,
    U_LDIR = -41,
    U_LOGONS = -42,
    U_FUL = -43,
    U_FDL = -44,
    U_BDLDAY = -45,
    U_TIMEON = -46,
    U_BDL = -47,
    U_BUL = -48,
    YEAR = -49,
    MONTH = -50,
    DAY = -51,
    DOW = -52,
    HOUR = -53,
    MIN = -54,
    SEC = -55,
    TIMEAP = -56,
    VER = -57,
    NOCHAR = -58,
    YESCHAR = -59,
    STRIPATX = -60,
    REPLACE = -61,
    STRIP = -62,
    INKEY = -63,
    TOSTRING = -64,
    MASK_PWD = -65,
    MASK_ALPHA = -66,
    MASK_NUM = -67,
    MASK_ALNUM = -68,
    MASK_FILE = -69,
    MASK_PATH = -70,
    MASK_ASCII = -71,
    CURCONF = -72,
    PCBDAT = -73,
    PPEPATH = -74,
    VALDATE = -75,
    VALTIME = -76,
    U_MSGRD = -77,
    U_MSGWR = -78,
    PCBNODE = -79,
    READLINE = -80,
    SYSOPSEC = -81,
    ONLOCAL = -82,
    UN_STAT = -83,
    UN_NAME = -84,
    UN_CITY = -85,
    UN_OPER = -86,
    CURSEC = -87,
    GETTOKEN = -88,
    MINLEFT = -89,
    MINON = -90,
    GETENV = -91,
    CALLID = -92,
    REGAL = -93,
    REGAH = -94,
    REGBL = -95,
    REGBH = -96,
    REGCL = -97,
    REGCH = -98,
    REGDL = -99,
    REGDH = -100,
    REGAX = -101,
    REGBX = -102,
    REGCX = -103,
    REGDX = -104,
    REGSI = -105,
    REGDI = -106,
    REGF = -107,
    REGCF = -108,
    REGDS = -109,
    REGES = -110,
    B2W = -111,
    PEEKB = -112,
    PEEKW = -113,
    MKADDR = -114,
    EXIST = -115,
    I2S = -116,
    S2I = -117,
    CARRIER = -118,
    TOKENSTR = -119,
    CDON = -120,
    LANGEXT = -121,
    ANSION = -122,
    VALCC = -123,
    FMTCC = -124,
    CCTYPE = -125,
    GETX = -126,
    GETY = -127,
    BAND = -128,
    BOR = -129,
    BXOR = -130,
    BNOT = -131,
    U_PWDHIST = -132,
    U_PWDLC = -133,
    U_PWDTC = -134,
    U_STAT = -135,
    DEFCOLOR = -136,
    ABS = -137,
    GRAFMODE = -138,
    PSA = -139,
    FILEINF = -140,
    PPENAME = -141,
    MKDATE = -142,
    CURCOLOR = -143,
    KINKEY = -144,
    MINKEY = -145,
    MAXNODE = -146,
    SLPATH = -147,
    HELPPATH = -148,
    TEMPPATH = -149,
    MODEM = -150,
    LOGGEDON = -151,
    CALLNUM = -152,
    MGETBYTE = -153,
    TOKCOUNT = -154,
    U_RECNUM = -155,
    U_INCONF = -156,
    PEEKDW = -157,
    DBGLEVEL = -158,
    SCRTEXT = -159,
    SHOWSTAT = -160,
    PAGESTAT = -161,

    REPLACESTR = -162,
    STRIPSTR = -163,
    TOBIGSTR = -164,
    TOBOOLEAN = -165,
    TOBYTE = -166,
    TODATE = -167,
    TODREAL = -168,
    TOEDATE = -169,
    TOINTEGER = -170,
    TOMONEY = -171,
    TOREAL = -172,
    TOSBYTE = -173,
    TOSWORD = -174,
    TOTIME = -175,
    TOUNSIGNED = -176,
    TOWORD = -177,
    MIXED = -178,
    ALIAS = -179,
    CONFREG = -180,
    CONFEXP = -181,
    CONFSEL = -182,
    CONFSYS = -183,
    CONFMW = -184,
    LPRINTED = -185,
    ISNONSTOP = -186,
    ERRCORRECT = -187,
    CONFALIAS = -188,
    USERALIAS = -189,
    CURUSER = -190,
    U_LMR = -191,
    CHATSTAT = -192,
    DEFANS = -193,
    LASTANS = -194,
    MEGANUM = -195,
    EVTTIMEADJ = -196,
    ISBITSET = -197,
    FMTREAL = -198,
    FLAGCNT = -199,
    KBDBUFSIZE = -200,
    PPLBUFSIZE = -201,
    KBDFILUSED = -202,
    LOMSGNUM = -203,
    HIMSGNUM = -204,

    DRIVESPACE = -205,
    OUTBYTES = -206,
    HICONFNUM = -207,
    INBYTES = -208,
    CRC32 = -209,
    PCBMAC = -210,
    ACTMSGNUM = -211,
    STACKLEFT = -212,
    STACKERR = -213,

    DGETALIAS = -214,
    DBOF = -215,
    DCHANGED = -216,
    DDECIMALS = -217,
    DDELETED = -218,
    DEOF = -219,
    DERR = -220,
    DFIELDS = -221,
    DLENGTH = -222,
    DNAME = -223,
    DRECCOUNT = -224,
    DRECNO = -225,
    DTYPE = -226,
    FNEXT = -227,
    DNEXT = -228,
    TODDATE = -229,
    DCLOSEALL = -230,
    DOPEN = -231,
    DCLOSE = -232,
    DSETALIAS = -233,
    DPACK = -234,
    DLOCKF = -235,
    DLOCK = -236,
    DLOCKR = -237,
    DUNLOCK = -238,
    DNOPEN = -239,
    DNCLOSE = -240,
    DNCLOSEALL = -241,
    DNEW = -242,
    DADD = -243,
    DAPPEND = -244,
    DTOP = -245,
    DGO = -246,
    DBOTTOM = -247,
    DSKIP = -248,
    DBLANK = -249,
    DDELETE = -250,
    DRECALL = -251,
    DTAG = -252,
    DSEEK = -253,
    DFBLANK = -254,
    DGET = -255,
    DPUT = -256,
    DFCOPY = -257,
    DSELECT = -258,
    DCHKSTAT = -259,

    PCBACCOUNT = -260,
    PCBACCSTAT = -261,
    DERRMSG = -262,
    ACCOUNT = -263,
    SCANMSGHDR = -264,
    CHECKRIP = -265,
    RIPVER = -266,
    QWKLIMITS = -267,
    FINDFIRST = -268,
    FINDNEXT = -269,
    USELMRS = -270,
    CONFINFO = -271,
    TINKEY = -272,
    CWD = -273,
    INSTRR = -274,
    FDORDAKA = -275,
    FDORDORG = -276,
    FDORDAREA = -277,
    FDOQRD = -278,
    GETDRIVE = -279,
    SETDRIVE = -280,
    BS2I = -281,
    BD2I = -282,
    I2BS = -283,
    I2BD = -284,
    FTELL = -285,
    OS = -286,
    SHORT_DESC = -287,
    GetBankBal = -288,
    GetMsgHdr = -289,
    SetMsgHdr = -290,
}
pub const LAST_FUNC: i16 = -290;
impl FuncOpCode {
    pub fn get_definition(self) -> &'static FunctionDefinition {
        let i = -(self as i16);
        &FUNCTION_DEFINITIONS[i as usize]
    }
}

impl Display for FuncOpCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{self:?}")
    }
}

type PredefFunc =
    fn(vm: &mut crate::vm::VirtualMachine, params: &[VariableValue]) -> Res<VariableValue>;

#[derive(Debug, PartialEq)]
pub struct FunctionDefinition {
    pub name: &'static str,
    pub version: u16,
    pub opcode: FuncOpCode,
    pub args: i8,
    pub function: PredefFunc,
}

impl FunctionDefinition {
    pub fn get_function_definition(str: &str) -> i32 {
        for (i, item) in FUNCTION_DEFINITIONS.iter().enumerate() {
            if item.name.eq_ignore_ascii_case(str) {
                return i as i32;
            }
        }
        -1
    }
}

pub static FUNCTION_DEFINITIONS: [FunctionDefinition; 294] = [
    FunctionDefinition {
        name: "END",
        version: 100,
        opcode: FuncOpCode::END,
        args: -1,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "CPAR",
        version: 100,
        opcode: FuncOpCode::CPAR,
        args: -1,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "UPLUS",
        version: 100,
        opcode: FuncOpCode::UPLUS,
        args: 0x10,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "UMINUS",
        version: 100,
        opcode: FuncOpCode::UMINUS,
        args: 0x10,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "EXP",
        version: 100,
        opcode: FuncOpCode::EXP,
        args: 0x11,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "TIMES",
        version: 100,
        opcode: FuncOpCode::TIMES,
        args: 0x11,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "DIVIDE",
        version: 100,
        opcode: FuncOpCode::DIVIDE,
        args: 0x11,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "MOD",
        version: 100,
        opcode: FuncOpCode::MOD,
        args: 0x11,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "PLUS",
        version: 100,
        opcode: FuncOpCode::PLUS,
        args: 0x11,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "MINUS",
        version: 100,
        opcode: FuncOpCode::MINUS,
        args: 0x11,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "EQ",
        version: 100,
        opcode: FuncOpCode::EQ,
        args: 0x11,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "NE",
        version: 100,
        opcode: FuncOpCode::NE,
        args: 0x11,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "LT",
        version: 100,
        opcode: FuncOpCode::LT,
        args: 0x11,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "LE",
        version: 100,
        opcode: FuncOpCode::LE,
        args: 0x11,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "GT",
        version: 100,
        opcode: FuncOpCode::GT,
        args: 0x11,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "GE",
        version: 100,
        opcode: FuncOpCode::GE,
        args: 0x11,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "NOT",
        version: 100,
        opcode: FuncOpCode::NOT,
        args: 0x10,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "AND",
        version: 100,
        opcode: FuncOpCode::AND,
        args: 0x11,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "OR",
        version: 100,
        opcode: FuncOpCode::OR,
        args: 0x11,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "OPAR",
        version: 100,
        opcode: FuncOpCode::OPAR,
        args: -1,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "Len",
        version: 100,
        opcode: FuncOpCode::LEN,
        args: 0x01,
        function: predefined_functions::len,
    },
    FunctionDefinition {
        name: "Lower",
        version: 100,
        opcode: FuncOpCode::LOWER,
        args: 0x01,
        function: predefined_functions::lower,
    },
    FunctionDefinition {
        name: "Upper",
        version: 100,
        opcode: FuncOpCode::UPPER,
        args: 0x01,
        function: predefined_functions::upper,
    },
    FunctionDefinition {
        name: "Mid",
        version: 100,
        opcode: FuncOpCode::MID,
        args: 0x03,
        function: predefined_functions::mid,
    },
    FunctionDefinition {
        name: "Left",
        version: 100,
        opcode: FuncOpCode::LEFT,
        args: 0x02,
        function: predefined_functions::left,
    },
    FunctionDefinition {
        name: "Right",
        version: 100,
        opcode: FuncOpCode::RIGHT,
        args: 0x02,
        function: predefined_functions::right,
    },
    FunctionDefinition {
        name: "Space",
        version: 100,
        opcode: FuncOpCode::SPACE,
        args: 0x01,
        function: predefined_functions::space,
    },
    FunctionDefinition {
        name: "FErr",
        version: 100,
        opcode: FuncOpCode::FERR,
        args: 0x01,
        function: predefined_functions::ferr,
    },
    FunctionDefinition {
        name: "Chr",
        version: 100,
        opcode: FuncOpCode::CHR,
        args: 0x01,
        function: predefined_functions::chr,
    },
    FunctionDefinition {
        name: "Asc",
        version: 100,
        opcode: FuncOpCode::ASC,
        args: 0x01,
        function: predefined_functions::asc,
    },
    FunctionDefinition {
        name: "InStr",
        version: 100,
        opcode: FuncOpCode::INSTR,
        args: 0x02,
        function: predefined_functions::instr,
    },
    FunctionDefinition {
        name: "Abort",
        version: 100,
        opcode: FuncOpCode::ABORT,
        args: 0x00,
        function: predefined_functions::abort,
    },
    FunctionDefinition {
        name: "LTrim",
        version: 100,
        opcode: FuncOpCode::LTRIM,
        args: 0x02,
        function: predefined_functions::ltrim,
    },
    FunctionDefinition {
        name: "RTrim",
        version: 100,
        opcode: FuncOpCode::RTRIM,
        args: 0x02,
        function: predefined_functions::rtrim,
    },
    FunctionDefinition {
        name: "Trim",
        version: 100,
        opcode: FuncOpCode::TRIM,
        args: 0x02,
        function: predefined_functions::trim,
    },
    FunctionDefinition {
        name: "Random",
        version: 100,
        opcode: FuncOpCode::RANDOM,
        args: 0x01,
        function: predefined_functions::random,
    },
    FunctionDefinition {
        name: "Date",
        version: 100,
        opcode: FuncOpCode::DATE,
        args: 0x00,
        function: predefined_functions::date,
    },
    FunctionDefinition {
        name: "Time",
        version: 100,
        opcode: FuncOpCode::TIME,
        args: 0x00,
        function: predefined_functions::time,
    },
    FunctionDefinition {
        name: "U_Name",
        version: 100,
        opcode: FuncOpCode::U_NAME,
        args: 0x00,
        function: predefined_functions::u_name,
    },
    FunctionDefinition {
        name: "U_LDate",
        version: 100,
        opcode: FuncOpCode::U_LDATE,
        args: 0x00,
        function: predefined_functions::u_ldate,
    },
    FunctionDefinition {
        name: "U_LTime",
        version: 100,
        opcode: FuncOpCode::U_LTIME,
        args: 0x00,
        function: predefined_functions::u_ltime,
    },
    FunctionDefinition {
        name: "U_LDir",
        version: 100,
        opcode: FuncOpCode::U_LDIR,
        args: 0x00,
        function: predefined_functions::u_ldir,
    },
    FunctionDefinition {
        name: "U_Logons",
        version: 100,
        opcode: FuncOpCode::U_LOGONS,
        args: 0x00,
        function: predefined_functions::u_logons,
    },
    FunctionDefinition {
        name: "U_FUl",
        version: 100,
        opcode: FuncOpCode::U_FUL,
        args: 0x00,
        function: predefined_functions::u_ful,
    },
    FunctionDefinition {
        name: "U_FDl",
        version: 100,
        opcode: FuncOpCode::U_FDL,
        args: 0x00,
        function: predefined_functions::u_fdl,
    },
    FunctionDefinition {
        name: "U_BDLDay",
        version: 100,
        opcode: FuncOpCode::U_BDLDAY,
        args: 0x00,
        function: predefined_functions::u_bdlday,
    },
    FunctionDefinition {
        name: "U_TimeOn",
        version: 100,
        opcode: FuncOpCode::U_TIMEON,
        args: 0x00,
        function: predefined_functions::u_timeon,
    },
    FunctionDefinition {
        name: "U_BDl",
        version: 100,
        opcode: FuncOpCode::U_BDL,
        args: 0x00,
        function: predefined_functions::u_bdl,
    },
    FunctionDefinition {
        name: "U_BUl",
        version: 100,
        opcode: FuncOpCode::U_BUL,
        args: 0x00,
        function: predefined_functions::u_bul,
    },
    FunctionDefinition {
        name: "Year",
        version: 100,
        opcode: FuncOpCode::YEAR,
        args: 0x01,
        function: predefined_functions::year,
    },
    FunctionDefinition {
        name: "Month",
        version: 100,
        opcode: FuncOpCode::MONTH,
        args: 0x01,
        function: predefined_functions::month,
    },
    FunctionDefinition {
        name: "Day",
        version: 100,
        opcode: FuncOpCode::DAY,
        args: 0x01,
        function: predefined_functions::day,
    },
    FunctionDefinition {
        name: "Dow",
        version: 100,
        opcode: FuncOpCode::DOW,
        args: 0x01,
        function: predefined_functions::dow,
    },
    FunctionDefinition {
        name: "Hour",
        version: 100,
        opcode: FuncOpCode::HOUR,
        args: 0x01,
        function: predefined_functions::hour,
    },
    FunctionDefinition {
        name: "Min",
        version: 100,
        opcode: FuncOpCode::MIN,
        args: 0x01,
        function: predefined_functions::min,
    },
    FunctionDefinition {
        name: "Sec",
        version: 100,
        opcode: FuncOpCode::SEC,
        args: 0x01,
        function: predefined_functions::sec,
    },
    FunctionDefinition {
        name: "TimeAP",
        version: 100,
        opcode: FuncOpCode::TIMEAP,
        args: 0x01,
        function: predefined_functions::timeap,
    },
    FunctionDefinition {
        name: "Ver",
        version: 100,
        opcode: FuncOpCode::VER,
        args: 0x00,
        function: predefined_functions::ver,
    },
    FunctionDefinition {
        name: "NoChar",
        version: 100,
        opcode: FuncOpCode::NOCHAR,
        args: 0x00,
        function: predefined_functions::nochar,
    },
    FunctionDefinition {
        name: "YesChar",
        version: 100,
        opcode: FuncOpCode::YESCHAR,
        args: 0x00,
        function: predefined_functions::yeschar,
    },
    FunctionDefinition {
        name: "StripATX",
        version: 100,
        opcode: FuncOpCode::STRIPATX,
        args: 0x01,
        function: predefined_functions::stripatx,
    },
    FunctionDefinition {
        name: "Replace",
        version: 100,
        opcode: FuncOpCode::REPLACE,
        args: 0x03,
        function: predefined_functions::replace,
    },
    FunctionDefinition {
        name: "Strip",
        version: 100,
        opcode: FuncOpCode::STRIP,
        args: 0x02,
        function: predefined_functions::strip,
    },
    FunctionDefinition {
        name: "InKey",
        version: 100,
        opcode: FuncOpCode::INKEY,
        args: 0x00,
        function: predefined_functions::inkey,
    },
    FunctionDefinition {
        name: "String",
        version: 100,
        opcode: FuncOpCode::TOSTRING,
        args: 0x01,
        function: predefined_functions::tostring,
    },
    FunctionDefinition {
        name: "Mask_Pwd",
        version: 100,
        opcode: FuncOpCode::MASK_PWD,
        args: 0x00,
        function: predefined_functions::mask_pwd,
    },
    FunctionDefinition {
        name: "Mask_Alpha",
        version: 100,
        opcode: FuncOpCode::MASK_ALPHA,
        args: 0x00,
        function: predefined_functions::mask_alpha,
    },
    FunctionDefinition {
        name: "Mask_Num",
        version: 100,
        opcode: FuncOpCode::MASK_NUM,
        args: 0x00,
        function: predefined_functions::mask_num,
    },
    FunctionDefinition {
        name: "Mask_Alnum",
        version: 100,
        opcode: FuncOpCode::MASK_ALNUM,
        args: 0x00,
        function: predefined_functions::mask_alnum,
    },
    FunctionDefinition {
        name: "Mask_File",
        version: 100,
        opcode: FuncOpCode::MASK_FILE,
        args: 0x00,
        function: predefined_functions::mask_file,
    },
    FunctionDefinition {
        name: "Mask_Path",
        version: 100,
        opcode: FuncOpCode::MASK_PATH,
        args: 0x00,
        function: predefined_functions::mask_path,
    },
    FunctionDefinition {
        name: "Mask_ASCII",
        version: 100,
        opcode: FuncOpCode::MASK_ASCII,
        args: 0x00,
        function: predefined_functions::mask_ascii,
    },
    FunctionDefinition {
        name: "CurConf",
        version: 100,
        opcode: FuncOpCode::CURCONF,
        args: 0x00,
        function: predefined_functions::curconf,
    },
    FunctionDefinition {
        name: "PCBDat",
        version: 100,
        opcode: FuncOpCode::PCBDAT,
        args: 0x00,
        function: predefined_functions::pcbdat,
    },
    FunctionDefinition {
        name: "PPEPath",
        version: 100,
        opcode: FuncOpCode::PPEPATH,
        args: 0x00,
        function: predefined_functions::ppepath,
    },
    FunctionDefinition {
        name: "ValDate",
        version: 100,
        opcode: FuncOpCode::VALDATE,
        args: 0x01,
        function: predefined_functions::valdate,
    },
    FunctionDefinition {
        name: "ValTime",
        version: 100,
        opcode: FuncOpCode::VALTIME,
        args: 0x01,
        function: predefined_functions::valtime,
    },
    FunctionDefinition {
        name: "U_MsgRd",
        version: 100,
        opcode: FuncOpCode::U_MSGRD,
        args: 0x00,
        function: predefined_functions::u_msgrd,
    },
    FunctionDefinition {
        name: "U_MsgWr",
        version: 100,
        opcode: FuncOpCode::U_MSGWR,
        args: 0x00,
        function: predefined_functions::u_msgwr,
    },
    FunctionDefinition {
        name: "PCBNode",
        version: 100,
        opcode: FuncOpCode::PCBNODE,
        args: 0x00,
        function: predefined_functions::pcbnode,
    },
    FunctionDefinition {
        name: "ReadLine",
        version: 100,
        opcode: FuncOpCode::READLINE,
        args: 0x02,
        function: predefined_functions::readline,
    },
    FunctionDefinition {
        name: "SysopSec",
        version: 100,
        opcode: FuncOpCode::SYSOPSEC,
        args: 0x00,
        function: predefined_functions::sysopsec,
    },
    FunctionDefinition {
        name: "OnLocal",
        version: 100,
        opcode: FuncOpCode::ONLOCAL,
        args: 0x00,
        function: predefined_functions::onlocal,
    },
    FunctionDefinition {
        name: "UN_Stat",
        version: 100,
        opcode: FuncOpCode::UN_STAT,
        args: 0x00,
        function: predefined_functions::un_stat,
    },
    FunctionDefinition {
        name: "UN_Name",
        version: 100,
        opcode: FuncOpCode::UN_NAME,
        args: 0x00,
        function: predefined_functions::un_name,
    },
    FunctionDefinition {
        name: "UN_City",
        version: 100,
        opcode: FuncOpCode::UN_CITY,
        args: 0x00,
        function: predefined_functions::un_city,
    },
    FunctionDefinition {
        name: "UN_Oper",
        version: 100,
        opcode: FuncOpCode::UN_OPER,
        args: 0x00,
        function: predefined_functions::un_oper,
    },
    FunctionDefinition {
        name: "CurSec",
        version: 100,
        opcode: FuncOpCode::CURSEC,
        args: 0x00,
        function: predefined_functions::cursec,
    },
    FunctionDefinition {
        name: "GetToken",
        version: 100,
        opcode: FuncOpCode::GETTOKEN,
        args: 0x00,
        function: predefined_functions::gettoken,
    },
    FunctionDefinition {
        name: "MinLeft",
        version: 100,
        opcode: FuncOpCode::MINLEFT,
        args: 0x00,
        function: predefined_functions::minleft,
    },
    FunctionDefinition {
        name: "MinOn",
        version: 100,
        opcode: FuncOpCode::MINON,
        args: 0x00,
        function: predefined_functions::minon,
    },
    FunctionDefinition {
        name: "GetEnv",
        version: 100,
        opcode: FuncOpCode::GETENV,
        args: 0x01,
        function: predefined_functions::getenv,
    },
    FunctionDefinition {
        name: "CallId",
        version: 100,
        opcode: FuncOpCode::CALLID,
        args: 0x00,
        function: predefined_functions::callid,
    },
    FunctionDefinition {
        name: "RegAL",
        version: 100,
        opcode: FuncOpCode::REGAL,
        args: 0x00,
        function: predefined_functions::regal,
    },
    FunctionDefinition {
        name: "RegAH",
        version: 100,
        opcode: FuncOpCode::REGAH,
        args: 0x00,
        function: predefined_functions::regah,
    },
    FunctionDefinition {
        name: "RegBL",
        version: 100,
        opcode: FuncOpCode::REGBL,
        args: 0x00,
        function: predefined_functions::regbl,
    },
    FunctionDefinition {
        name: "RegBH",
        version: 100,
        opcode: FuncOpCode::REGBH,
        args: 0x00,
        function: predefined_functions::regbh,
    },
    FunctionDefinition {
        name: "RegCL",
        version: 100,
        opcode: FuncOpCode::REGCL,
        args: 0x00,
        function: predefined_functions::regcl,
    },
    FunctionDefinition {
        name: "RegCH",
        version: 100,
        opcode: FuncOpCode::REGCH,
        args: 0x00,
        function: predefined_functions::regch,
    },
    FunctionDefinition {
        name: "RegDL",
        version: 100,
        opcode: FuncOpCode::REGDL,
        args: 0x00,
        function: predefined_functions::regdl,
    },
    FunctionDefinition {
        name: "RegDH",
        version: 100,
        opcode: FuncOpCode::REGDH,
        args: 0x00,
        function: predefined_functions::regdh,
    },
    FunctionDefinition {
        name: "RegAX",
        version: 100,
        opcode: FuncOpCode::REGAX,
        args: 0x00,
        function: predefined_functions::regax,
    },
    FunctionDefinition {
        name: "RegBX",
        version: 100,
        opcode: FuncOpCode::REGBX,
        args: 0x00,
        function: predefined_functions::regbx,
    },
    FunctionDefinition {
        name: "RegCX",
        version: 100,
        opcode: FuncOpCode::REGCX,
        args: 0x00,
        function: predefined_functions::regcx,
    },
    FunctionDefinition {
        name: "RegDX",
        version: 100,
        opcode: FuncOpCode::REGDX,
        args: 0x00,
        function: predefined_functions::regdx,
    },
    FunctionDefinition {
        name: "RegSI",
        version: 100,
        opcode: FuncOpCode::REGSI,
        args: 0x00,
        function: predefined_functions::regsi,
    },
    FunctionDefinition {
        name: "RegDI",
        version: 100,
        opcode: FuncOpCode::REGDI,
        args: 0x00,
        function: predefined_functions::regdi,
    },
    FunctionDefinition {
        name: "RegF",
        version: 100,
        opcode: FuncOpCode::REGF,
        args: 0x00,
        function: predefined_functions::regf,
    },
    FunctionDefinition {
        name: "RegCF",
        version: 100,
        opcode: FuncOpCode::REGCF,
        args: 0x00,
        function: predefined_functions::regcf,
    },
    FunctionDefinition {
        name: "RegDS",
        version: 100,
        opcode: FuncOpCode::REGDS,
        args: 0x00,
        function: predefined_functions::regds,
    },
    FunctionDefinition {
        name: "RegES",
        version: 100,
        opcode: FuncOpCode::REGES,
        args: 0x00,
        function: predefined_functions::reges,
    },
    FunctionDefinition {
        name: "B2W",
        version: 100,
        opcode: FuncOpCode::B2W,
        args: 0x02,
        function: predefined_functions::b2w,
    },
    FunctionDefinition {
        name: "PeekB",
        version: 100,
        opcode: FuncOpCode::PEEKB,
        args: 0x01,
        function: predefined_functions::peekb,
    },
    FunctionDefinition {
        name: "PeekW",
        version: 100,
        opcode: FuncOpCode::PEEKW,
        args: 0x01,
        function: predefined_functions::peekw,
    },
    FunctionDefinition {
        name: "MkAddr",
        version: 100,
        opcode: FuncOpCode::MKADDR,
        args: 0x02,
        function: predefined_functions::mkaddr,
    },
    FunctionDefinition {
        name: "Exist",
        version: 100,
        opcode: FuncOpCode::EXIST,
        args: 0x01,
        function: predefined_functions::exist,
    },
    FunctionDefinition {
        name: "I2S",
        version: 100,
        opcode: FuncOpCode::I2S,
        args: 0x02,
        function: predefined_functions::i2s,
    },
    FunctionDefinition {
        name: "S2I",
        version: 100,
        opcode: FuncOpCode::S2I,
        args: 0x02,
        function: predefined_functions::s2i,
    },
    FunctionDefinition {
        name: "Carrier",
        version: 100,
        opcode: FuncOpCode::CARRIER,
        args: 0x00,
        function: predefined_functions::carrier,
    },
    FunctionDefinition {
        name: "TokenStr",
        version: 100,
        opcode: FuncOpCode::TOKENSTR,
        args: 0x00,
        function: predefined_functions::tokenstr,
    },
    FunctionDefinition {
        name: "CDOn",
        version: 100,
        opcode: FuncOpCode::CDON,
        args: 0x00,
        function: predefined_functions::cdon,
    },
    FunctionDefinition {
        name: "LangExt",
        version: 100,
        opcode: FuncOpCode::LANGEXT,
        args: 0x00,
        function: predefined_functions::langext,
    },
    FunctionDefinition {
        name: "ANSIOn",
        version: 100,
        opcode: FuncOpCode::ANSION,
        args: 0x00,
        function: predefined_functions::ansion,
    },
    FunctionDefinition {
        name: "ValCC",
        version: 100,
        opcode: FuncOpCode::VALCC,
        args: 0x01,
        function: predefined_functions::valcc,
    },
    FunctionDefinition {
        name: "FmtCC",
        version: 100,
        opcode: FuncOpCode::FMTCC,
        args: 0x01,
        function: predefined_functions::fmtcc,
    },
    FunctionDefinition {
        name: "CCType",
        version: 100,
        opcode: FuncOpCode::CCTYPE,
        args: 0x01,
        function: predefined_functions::cctype,
    },
    FunctionDefinition {
        name: "GetX",
        version: 100,
        opcode: FuncOpCode::GETX,
        args: 0x00,
        function: predefined_functions::getx,
    },
    FunctionDefinition {
        name: "GetY",
        version: 100,
        opcode: FuncOpCode::GETY,
        args: 0x00,
        function: predefined_functions::gety,
    },
    FunctionDefinition {
        name: "And",
        version: 100,
        opcode: FuncOpCode::BAND,
        args: 0x02,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "Or",
        version: 100,
        opcode: FuncOpCode::BOR,
        args: 0x02,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "Xor",
        version: 100,
        opcode: FuncOpCode::BXOR,
        args: 0x02,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "Not",
        version: 100,
        opcode: FuncOpCode::BNOT,
        args: 0x01,
        function: predefined_functions::invalid,
    },
    FunctionDefinition {
        name: "U_PwdHist",
        version: 100,
        opcode: FuncOpCode::U_PWDHIST,
        args: 0x01,
        function: predefined_functions::u_pwdhist,
    },
    FunctionDefinition {
        name: "U_PwdLc",
        version: 100,
        opcode: FuncOpCode::U_PWDLC,
        args: 0x00,
        function: predefined_functions::u_pwdlc,
    },
    FunctionDefinition {
        name: "U_PwdTc",
        version: 100,
        opcode: FuncOpCode::U_PWDTC,
        args: 0x00,
        function: predefined_functions::u_pwdtc,
    },
    FunctionDefinition {
        name: "U_Stat",
        version: 100,
        opcode: FuncOpCode::U_STAT,
        args: 0x01,
        function: predefined_functions::u_stat,
    },
    FunctionDefinition {
        name: "DefColor",
        version: 100,
        opcode: FuncOpCode::DEFCOLOR,
        args: 0x00,
        function: predefined_functions::defcolor,
    },
    FunctionDefinition {
        name: "Abs",
        version: 100,
        opcode: FuncOpCode::ABS,
        args: 0x01,
        function: predefined_functions::abs,
    },
    FunctionDefinition {
        name: "GrafMode",
        version: 100,
        opcode: FuncOpCode::GRAFMODE,
        args: 0x00,
        function: predefined_functions::grafmode,
    },
    FunctionDefinition {
        name: "PSA",
        version: 100,
        opcode: FuncOpCode::PSA,
        args: 0x01,
        function: predefined_functions::psa,
    },
    FunctionDefinition {
        name: "FileInf",
        version: 100,
        opcode: FuncOpCode::FILEINF,
        args: 0x02,
        function: predefined_functions::fileinf,
    },
    FunctionDefinition {
        name: "PPEName",
        version: 100,
        opcode: FuncOpCode::PPENAME,
        args: 0x00,
        function: predefined_functions::ppename,
    },
    FunctionDefinition {
        name: "MkDate",
        version: 100,
        opcode: FuncOpCode::MKDATE,
        args: 0x03,
        function: predefined_functions::mkdate,
    },
    FunctionDefinition {
        name: "CurColor",
        version: 100,
        opcode: FuncOpCode::CURCOLOR,
        args: 0x00,
        function: predefined_functions::curcolor,
    },
    FunctionDefinition {
        name: "KInkey",
        version: 100,
        opcode: FuncOpCode::KINKEY,
        args: 0x00,
        function: predefined_functions::kinkey,
    },
    FunctionDefinition {
        name: "MInkey",
        version: 100,
        opcode: FuncOpCode::MINKEY,
        args: 0x00,
        function: predefined_functions::minkey,
    },
    FunctionDefinition {
        name: "MaxNode",
        version: 100,
        opcode: FuncOpCode::MAXNODE,
        args: 0x00,
        function: predefined_functions::maxnode,
    },
    FunctionDefinition {
        name: "SLPath",
        version: 100,
        opcode: FuncOpCode::SLPATH,
        args: 0x00,
        function: predefined_functions::slpath,
    },
    FunctionDefinition {
        name: "HelpPath",
        version: 100,
        opcode: FuncOpCode::HELPPATH,
        args: 0x00,
        function: predefined_functions::helppath,
    },
    FunctionDefinition {
        name: "TempPath",
        version: 100,
        opcode: FuncOpCode::TEMPPATH,
        args: 0x00,
        function: predefined_functions::temppath,
    },
    FunctionDefinition {
        name: "Modem",
        version: 100,
        opcode: FuncOpCode::MODEM,
        args: 0x00,
        function: predefined_functions::modem,
    },
    FunctionDefinition {
        name: "LoggedOn",
        version: 100,
        opcode: FuncOpCode::LOGGEDON,
        args: 0x00,
        function: predefined_functions::loggedon,
    },
    FunctionDefinition {
        name: "CallNum",
        version: 100,
        opcode: FuncOpCode::CALLNUM,
        args: 0x00,
        function: predefined_functions::callnum,
    },
    FunctionDefinition {
        name: "MGetByte",
        version: 100,
        opcode: FuncOpCode::MGETBYTE,
        args: 0x00,
        function: predefined_functions::mgetbyte,
    },
    FunctionDefinition {
        name: "TokCount",
        version: 100,
        opcode: FuncOpCode::TOKCOUNT,
        args: 0x00,
        function: predefined_functions::tokcount,
    },
    FunctionDefinition {
        name: "U_RecNum",
        version: 100,
        opcode: FuncOpCode::U_RECNUM,
        args: 0x01,
        function: predefined_functions::u_recnum,
    },
    FunctionDefinition {
        name: "U_InConf",
        version: 100,
        opcode: FuncOpCode::U_INCONF,
        args: 0x02,
        function: predefined_functions::u_inconf,
    },
    FunctionDefinition {
        name: "PeekDW",
        version: 100,
        opcode: FuncOpCode::PEEKDW,
        args: 0x01,
        function: predefined_functions::peekdw,
    },
    FunctionDefinition {
        name: "DbgLevel",
        version: 100,
        opcode: FuncOpCode::DBGLEVEL,
        args: 0x00,
        function: predefined_functions::dbglevel,
    },
    FunctionDefinition {
        name: "ScrText",
        version: 100,
        opcode: FuncOpCode::SCRTEXT,
        args: 0x04,
        function: predefined_functions::scrtext,
    },
    FunctionDefinition {
        name: "ShowStat",
        version: 100,
        opcode: FuncOpCode::SHOWSTAT,
        args: 0x00,
        function: predefined_functions::showstat,
    },
    FunctionDefinition {
        name: "PageStat",
        version: 100,
        opcode: FuncOpCode::PAGESTAT,
        args: 0x00,
        function: predefined_functions::pagestat,
    },
    FunctionDefinition {
        name: "ReplaceStr",
        version: 200,
        opcode: FuncOpCode::REPLACESTR,
        args: 0x03,
        function: predefined_functions::replacestr,
    },
    FunctionDefinition {
        name: "StripStr",
        version: 200,
        opcode: FuncOpCode::STRIPSTR,
        args: 0x02,
        function: predefined_functions::stripstr,
    },
    FunctionDefinition {
        name: "ToBigStr",
        version: 200,
        opcode: FuncOpCode::TOBIGSTR,
        args: 0x01,
        function: predefined_functions::tobigstr,
    },
    FunctionDefinition {
        name: "ToBoolean",
        version: 200,
        opcode: FuncOpCode::TOBOOLEAN,
        args: 0x01,
        function: predefined_functions::toboolean,
    },
    FunctionDefinition {
        name: "ToByte",
        version: 200,
        opcode: FuncOpCode::TOBYTE,
        args: 0x01,
        function: predefined_functions::tobyte,
    },
    FunctionDefinition {
        name: "ToDate",
        version: 200,
        opcode: FuncOpCode::TODATE,
        args: 0x01,
        function: predefined_functions::todate,
    },
    FunctionDefinition {
        name: "ToDReal",
        version: 200,
        opcode: FuncOpCode::TODREAL,
        args: 0x01,
        function: predefined_functions::todreal,
    },
    FunctionDefinition {
        name: "ToEDate",
        version: 200,
        opcode: FuncOpCode::TOEDATE,
        args: 0x01,
        function: predefined_functions::toedate,
    },
    FunctionDefinition {
        name: "ToInteger",
        version: 200,
        opcode: FuncOpCode::TOINTEGER,
        args: 0x01,
        function: predefined_functions::tointeger,
    },
    FunctionDefinition {
        name: "ToMoney",
        version: 200,
        opcode: FuncOpCode::TOMONEY,
        args: 0x01,
        function: predefined_functions::tomoney,
    },
    FunctionDefinition {
        name: "ToReal",
        version: 200,
        opcode: FuncOpCode::TOREAL,
        args: 0x01,
        function: predefined_functions::toreal,
    },
    FunctionDefinition {
        name: "ToSByte",
        version: 200,
        opcode: FuncOpCode::TOSBYTE,
        args: 0x01,
        function: predefined_functions::tosbyte,
    },
    FunctionDefinition {
        name: "ToSWord",
        version: 200,
        opcode: FuncOpCode::TOSWORD,
        args: 0x01,
        function: predefined_functions::tosword,
    },
    FunctionDefinition {
        name: "ToTime",
        version: 200,
        opcode: FuncOpCode::TOTIME,
        args: 0x01,
        function: predefined_functions::totime,
    },
    FunctionDefinition {
        name: "ToUnsigned",
        version: 200,
        opcode: FuncOpCode::TOUNSIGNED,
        args: 0x01,
        function: predefined_functions::tounsigned,
    },
    FunctionDefinition {
        name: "ToWord",
        version: 200,
        opcode: FuncOpCode::TOWORD,
        args: 0x01,
        function: predefined_functions::toword,
    },
    FunctionDefinition {
        name: "Mixed",
        version: 200,
        opcode: FuncOpCode::MIXED,
        args: 0x01,
        function: predefined_functions::mixed,
    },
    FunctionDefinition {
        name: "Alias",
        version: 200,
        opcode: FuncOpCode::ALIAS,
        args: 0x00,
        function: predefined_functions::alias,
    },
    FunctionDefinition {
        name: "ConfReg",
        version: 200,
        opcode: FuncOpCode::CONFREG,
        args: 0x01,
        function: predefined_functions::confreg,
    },
    FunctionDefinition {
        name: "ConfExp",
        version: 200,
        opcode: FuncOpCode::CONFEXP,
        args: 0x01,
        function: predefined_functions::confexp,
    },
    FunctionDefinition {
        name: "ConfSel",
        version: 200,
        opcode: FuncOpCode::CONFSEL,
        args: 0x01,
        function: predefined_functions::confsel,
    },
    FunctionDefinition {
        name: "ConfSys",
        version: 200,
        opcode: FuncOpCode::CONFSYS,
        args: 0x01,
        function: predefined_functions::confsys,
    },
    FunctionDefinition {
        name: "ConfMW",
        version: 200,
        opcode: FuncOpCode::CONFMW,
        args: 0x01,
        function: predefined_functions::confmw,
    },
    FunctionDefinition {
        name: "LPrinted",
        version: 200,
        opcode: FuncOpCode::LPRINTED,
        args: 0x00,
        function: predefined_functions::lprinted,
    },
    FunctionDefinition {
        name: "IsNonStop",
        version: 200,
        opcode: FuncOpCode::ISNONSTOP,
        args: 0x00,
        function: predefined_functions::isnonstop,
    },
    FunctionDefinition {
        name: "ErrCorrect",
        version: 200,
        opcode: FuncOpCode::ERRCORRECT,
        args: 0x00,
        function: predefined_functions::errcorrect,
    },
    FunctionDefinition {
        name: "ConfAlias",
        version: 200,
        opcode: FuncOpCode::CONFALIAS,
        args: 0x00,
        function: predefined_functions::confalias,
    },
    FunctionDefinition {
        name: "UserAlias",
        version: 200,
        opcode: FuncOpCode::USERALIAS,
        args: 0x00,
        function: predefined_functions::useralias,
    },
    FunctionDefinition {
        name: "CurUser",
        version: 200,
        opcode: FuncOpCode::CURUSER,
        args: 0x00,
        function: predefined_functions::curuser,
    },
    FunctionDefinition {
        name: "U_LMR",
        version: 200,
        opcode: FuncOpCode::U_LMR,
        args: 0x01,
        function: predefined_functions::u_lmr,
    },
    FunctionDefinition {
        name: "ChatStat",
        version: 200,
        opcode: FuncOpCode::CHATSTAT,
        args: 0x00,
        function: predefined_functions::chatstat,
    },
    FunctionDefinition {
        name: "DefAns",
        version: 200,
        opcode: FuncOpCode::DEFANS,
        args: 0x00,
        function: predefined_functions::defans,
    },
    FunctionDefinition {
        name: "LastAns",
        version: 200,
        opcode: FuncOpCode::LASTANS,
        args: 0x00,
        function: predefined_functions::lastans,
    },
    FunctionDefinition {
        name: "MegaNum",
        version: 200,
        opcode: FuncOpCode::MEGANUM,
        args: 0x01,
        function: predefined_functions::meganum,
    },
    FunctionDefinition {
        name: "EVTTimeAdj",
        version: 200,
        opcode: FuncOpCode::EVTTIMEADJ,
        args: 0x00,
        function: predefined_functions::evttimeadj,
    },
    FunctionDefinition {
        name: "IsBitSet",
        version: 200,
        opcode: FuncOpCode::ISBITSET,
        args: 0x02,
        function: predefined_functions::isbitset,
    },
    FunctionDefinition {
        name: "FmtReal",
        version: 200,
        opcode: FuncOpCode::FMTREAL,
        args: 0x03,
        function: predefined_functions::fmtreal,
    },
    FunctionDefinition {
        name: "FlagCNT",
        version: 200,
        opcode: FuncOpCode::FLAGCNT,
        args: 0x00,
        function: predefined_functions::flagcnt,
    },
    FunctionDefinition {
        name: "KBDBufSize",
        version: 200,
        opcode: FuncOpCode::KBDBUFSIZE,
        args: 0x00,
        function: predefined_functions::kbdbufsize,
    },
    FunctionDefinition {
        name: "PPLBufSize",
        version: 200,
        opcode: FuncOpCode::PPLBUFSIZE,
        args: 0x00,
        function: predefined_functions::pplbufsize,
    },
    FunctionDefinition {
        name: "KBDFilUsued",
        version: 200,
        opcode: FuncOpCode::KBDFILUSED,
        args: 0x00,
        function: predefined_functions::kbdfilusued,
    },
    FunctionDefinition {
        name: "LoMsgNum",
        version: 200,
        opcode: FuncOpCode::LOMSGNUM,
        args: 0x00,
        function: predefined_functions::lomsgnum,
    },
    FunctionDefinition {
        name: "HiMsgNum",
        version: 200,
        opcode: FuncOpCode::HIMSGNUM,
        args: 0x00,
        function: predefined_functions::himsgnum,
    },
    FunctionDefinition {
        name: "DriveSpace",
        version: 200,
        opcode: FuncOpCode::DRIVESPACE,
        args: 0x01,
        function: predefined_functions::drivespace,
    },
    FunctionDefinition {
        name: "OutBytes",
        version: 200,
        opcode: FuncOpCode::OUTBYTES,
        args: 0x00,
        function: predefined_functions::outbytes,
    },
    FunctionDefinition {
        name: "HiConfNum",
        version: 200,
        opcode: FuncOpCode::HICONFNUM,
        args: 0x00,
        function: predefined_functions::hiconfnum,
    },
    FunctionDefinition {
        name: "InBytes",
        version: 200,
        opcode: FuncOpCode::INBYTES,
        args: 0x00,
        function: predefined_functions::inbytes,
    },
    FunctionDefinition {
        name: "CRC32",
        version: 200,
        opcode: FuncOpCode::CRC32,
        args: 0x02,
        function: predefined_functions::crc32,
    },
    FunctionDefinition {
        name: "PcbMac",
        version: 200,
        opcode: FuncOpCode::PCBMAC,
        args: 0x01,
        function: predefined_functions::pcbmac,
    },
    FunctionDefinition {
        name: "ActMSGNum",
        version: 200,
        opcode: FuncOpCode::ACTMSGNUM,
        args: 0x00,
        function: predefined_functions::actmsgnum,
    },
    FunctionDefinition {
        name: "StackLeft",
        version: 200,
        opcode: FuncOpCode::STACKLEFT,
        args: 0x00,
        function: predefined_functions::stackleft,
    },
    FunctionDefinition {
        name: "StackErr",
        version: 200,
        opcode: FuncOpCode::STACKERR,
        args: 0x00,
        function: predefined_functions::stackerr,
    },
    FunctionDefinition {
        name: "DGetAlias",
        version: 300,
        opcode: FuncOpCode::DGETALIAS,
        args: 0x01,
        function: predefined_functions::dgetalias,
    },
    FunctionDefinition {
        name: "DBOF",
        version: 300,
        opcode: FuncOpCode::DBOF,
        args: 0x01,
        function: predefined_functions::dbof,
    },
    FunctionDefinition {
        name: "DChanged",
        version: 300,
        opcode: FuncOpCode::DCHANGED,
        args: 0x01,
        function: predefined_functions::dchanged,
    },
    FunctionDefinition {
        name: "DDecimals",
        version: 300,
        opcode: FuncOpCode::DDECIMALS,
        args: 0x02,
        function: predefined_functions::ddecimals,
    },
    FunctionDefinition {
        name: "DDeleted",
        version: 300,
        opcode: FuncOpCode::DDELETED,
        args: 0x01,
        function: predefined_functions::ddeleted,
    },
    FunctionDefinition {
        name: "DEof",
        version: 300,
        opcode: FuncOpCode::DEOF,
        args: 0x01,
        function: predefined_functions::deof,
    },
    FunctionDefinition {
        name: "DErr",
        version: 300,
        opcode: FuncOpCode::DERR,
        args: 0x01,
        function: predefined_functions::derr,
    },
    FunctionDefinition {
        name: "DFields",
        version: 300,
        opcode: FuncOpCode::DFIELDS,
        args: 0x01,
        function: predefined_functions::dfields,
    },
    FunctionDefinition {
        name: "DLength",
        version: 300,
        opcode: FuncOpCode::DLENGTH,
        args: 0x02,
        function: predefined_functions::dlength,
    },
    FunctionDefinition {
        name: "DName",
        version: 300,
        opcode: FuncOpCode::DNAME,
        args: 0x02,
        function: predefined_functions::dname,
    },
    FunctionDefinition {
        name: "DRecCount",
        version: 300,
        opcode: FuncOpCode::DRECCOUNT,
        args: 0x01,
        function: predefined_functions::dreccount,
    },
    FunctionDefinition {
        name: "DRecNo",
        version: 300,
        opcode: FuncOpCode::DRECNO,
        args: 0x01,
        function: predefined_functions::drecno,
    },
    FunctionDefinition {
        name: "DType",
        version: 300,
        opcode: FuncOpCode::DTYPE,
        args: 0x02,
        function: predefined_functions::dtype,
    },
    FunctionDefinition {
        name: "FNext",
        version: 300,
        opcode: FuncOpCode::FNEXT,
        args: 0x00,
        function: predefined_functions::fnext,
    },
    FunctionDefinition {
        name: "DNext",
        version: 300,
        opcode: FuncOpCode::DNEXT,
        args: 0x00,
        function: predefined_functions::dnext,
    },
    FunctionDefinition {
        name: "ToDDate",
        version: 300,
        opcode: FuncOpCode::TODDATE,
        args: 0x01,
        function: predefined_functions::toddate,
    },
    FunctionDefinition {
        name: "DCloseAll",
        version: 300,
        opcode: FuncOpCode::DCLOSEALL,
        args: 0x00,
        function: predefined_functions::dcloseall,
    },
    FunctionDefinition {
        name: "DOpen",
        version: 300,
        opcode: FuncOpCode::DOPEN,
        args: 0x03,
        function: predefined_functions::dopen,
    },
    FunctionDefinition {
        name: "DClose",
        version: 300,
        opcode: FuncOpCode::DCLOSE,
        args: 0x01,
        function: predefined_functions::dclose,
    },
    FunctionDefinition {
        name: "DSetAlias",
        version: 300,
        opcode: FuncOpCode::DSETALIAS,
        args: 0x02,
        function: predefined_functions::dsetalias,
    },
    FunctionDefinition {
        name: "DPack",
        version: 300,
        opcode: FuncOpCode::DPACK,
        args: 0x01,
        function: predefined_functions::dpack,
    },
    FunctionDefinition {
        name: "DLockF",
        version: 300,
        opcode: FuncOpCode::DLOCKF,
        args: 0x01,
        function: predefined_functions::dlockf,
    },
    FunctionDefinition {
        name: "DLock",
        version: 300,
        opcode: FuncOpCode::DLOCK,
        args: 0x01,
        function: predefined_functions::dlock,
    },
    FunctionDefinition {
        name: "DLockR",
        version: 300,
        opcode: FuncOpCode::DLOCKR,
        args: 0x02,
        function: predefined_functions::dlockr,
    },
    FunctionDefinition {
        name: "DUnLock",
        version: 300,
        opcode: FuncOpCode::DUNLOCK,
        args: 0x01,
        function: predefined_functions::dunlock,
    },
    FunctionDefinition {
        name: "DNOpen",
        version: 300,
        opcode: FuncOpCode::DNOPEN,
        args: 0x02,
        function: predefined_functions::dnopen,
    },
    FunctionDefinition {
        name: "DNClose",
        version: 300,
        opcode: FuncOpCode::DNCLOSE,
        args: 0x02,
        function: predefined_functions::dnclose,
    },
    FunctionDefinition {
        name: "DNCloseAll",
        version: 300,
        opcode: FuncOpCode::DNCLOSEALL,
        args: 0x01,
        function: predefined_functions::dncloseall,
    },
    FunctionDefinition {
        name: "DNew",
        version: 300,
        opcode: FuncOpCode::DNEW,
        args: 0x01,
        function: predefined_functions::dnew,
    },
    FunctionDefinition {
        name: "DAdd",
        version: 300,
        opcode: FuncOpCode::DADD,
        args: 0x01,
        function: predefined_functions::dadd,
    },
    FunctionDefinition {
        name: "DAppend",
        version: 300,
        opcode: FuncOpCode::DAPPEND,
        args: 0x01,
        function: predefined_functions::dappend,
    },
    FunctionDefinition {
        name: "DTop",
        version: 300,
        opcode: FuncOpCode::DTOP,
        args: 0x01,
        function: predefined_functions::dtop,
    },
    FunctionDefinition {
        name: "DGo",
        version: 300,
        opcode: FuncOpCode::DGO,
        args: 0x02,
        function: predefined_functions::dgo,
    },
    FunctionDefinition {
        name: "DBottom",
        version: 300,
        opcode: FuncOpCode::DBOTTOM,
        args: 0x01,
        function: predefined_functions::dbottom,
    },
    FunctionDefinition {
        name: "DSkip",
        version: 300,
        opcode: FuncOpCode::DSKIP,
        args: 0x02,
        function: predefined_functions::dskip,
    },
    FunctionDefinition {
        name: "DBLank",
        version: 300,
        opcode: FuncOpCode::DBLANK,
        args: 0x01,
        function: predefined_functions::dblank,
    },
    FunctionDefinition {
        name: "DDelete",
        version: 300,
        opcode: FuncOpCode::DDELETE,
        args: 0x01,
        function: predefined_functions::ddelete,
    },
    FunctionDefinition {
        name: "DRecall",
        version: 300,
        opcode: FuncOpCode::DRECALL,
        args: 0x01,
        function: predefined_functions::drecall,
    },
    FunctionDefinition {
        name: "DTag",
        version: 300,
        opcode: FuncOpCode::DTAG,
        args: 0x02,
        function: predefined_functions::dtag,
    },
    FunctionDefinition {
        name: "DSeek",
        version: 300,
        opcode: FuncOpCode::DSEEK,
        args: 0x02,
        function: predefined_functions::dseek,
    },
    FunctionDefinition {
        name: "DFBlank",
        version: 300,
        opcode: FuncOpCode::DFBLANK,
        args: 0x02,
        function: predefined_functions::dfblank,
    },
    FunctionDefinition {
        name: "DGet",
        version: 300,
        opcode: FuncOpCode::DGET,
        args: 0x02,
        function: predefined_functions::dget,
    },
    FunctionDefinition {
        name: "DPut",
        version: 300,
        opcode: FuncOpCode::DPUT,
        args: 0x03,
        function: predefined_functions::dput,
    },
    FunctionDefinition {
        name: "DFCopy",
        version: 300,
        opcode: FuncOpCode::DFCOPY,
        args: 0x04,
        function: predefined_functions::dfcopy,
    },
    FunctionDefinition {
        name: "DSelect",
        version: 300,
        opcode: FuncOpCode::DSELECT,
        args: 0x01,
        function: predefined_functions::dselect,
    },
    FunctionDefinition {
        name: "DChkStat",
        version: 300,
        opcode: FuncOpCode::DCHKSTAT,
        args: 0x01,
        function: predefined_functions::dchkstat,
    },
    FunctionDefinition {
        name: "PCBAccount",
        version: 300,
        opcode: FuncOpCode::PCBACCOUNT,
        args: 0x01,
        function: predefined_functions::pcbaccount,
    },
    FunctionDefinition {
        name: "PCBAccStat",
        version: 300,
        opcode: FuncOpCode::PCBACCSTAT,
        args: 0x01,
        function: predefined_functions::pcbaccstat,
    },
    FunctionDefinition {
        name: "DErrMsg",
        version: 300,
        opcode: FuncOpCode::DERRMSG,
        args: 0x01,
        function: predefined_functions::derrmsg,
    },
    FunctionDefinition {
        name: "Account",
        version: 300,
        opcode: FuncOpCode::ACCOUNT,
        args: 0x01,
        function: predefined_functions::account,
    },
    FunctionDefinition {
        name: "ScanMsgHdr",
        version: 300,
        opcode: FuncOpCode::SCANMSGHDR,
        args: 0x04,
        function: predefined_functions::scanmsghdr,
    },
    FunctionDefinition {
        name: "CheckRIP",
        version: 300,
        opcode: FuncOpCode::CHECKRIP,
        args: 0x00,
        function: predefined_functions::checkrip,
    },
    FunctionDefinition {
        name: "RIPVer",
        version: 300,
        opcode: FuncOpCode::RIPVER,
        args: 0x00,
        function: predefined_functions::ripver,
    },
    FunctionDefinition {
        name: "QWKLimits",
        version: 300,
        opcode: FuncOpCode::QWKLIMITS,
        args: 0x01,
        function: predefined_functions::qwklimits,
    },
    FunctionDefinition {
        name: "FindFirst",
        version: 300,
        opcode: FuncOpCode::FINDFIRST,
        args: 0x01,
        function: predefined_functions::findfirst,
    },
    FunctionDefinition {
        name: "FindNext",
        version: 300,
        opcode: FuncOpCode::FINDNEXT,
        args: 0x00,
        function: predefined_functions::findnext,
    },
    FunctionDefinition {
        name: "USelMrs",
        version: 300,
        opcode: FuncOpCode::USELMRS,
        args: 0x00,
        function: predefined_functions::uselmrs,
    },
    FunctionDefinition {
        name: "ConfInfo",
        version: 300,
        opcode: FuncOpCode::CONFINFO,
        args: 0x02,
        function: predefined_functions::confinfo,
    },
    FunctionDefinition {
        name: "TInkey",
        version: 300,
        opcode: FuncOpCode::TINKEY,
        args: 0x01,
        function: predefined_functions::tinkey,
    },
    FunctionDefinition {
        name: "CWD",
        version: 300,
        opcode: FuncOpCode::CWD,
        args: 0x00,
        function: predefined_functions::cwd,
    },
    FunctionDefinition {
        name: "InStrr",
        version: 300,
        opcode: FuncOpCode::INSTRR,
        args: 0x02,
        function: predefined_functions::instrr,
    },
    FunctionDefinition {
        name: "FDORDAKA",
        version: 300,
        opcode: FuncOpCode::FDORDAKA,
        args: 0x01,
        function: predefined_functions::fdordaka,
    },
    FunctionDefinition {
        name: "FDORDOrg",
        version: 300,
        opcode: FuncOpCode::FDORDORG,
        args: 0x01,
        function: predefined_functions::fdordorg,
    },
    FunctionDefinition {
        name: "FDORDArea",
        version: 300,
        opcode: FuncOpCode::FDORDAREA,
        args: 0x01,
        function: predefined_functions::fdordarea,
    },
    FunctionDefinition {
        name: "FDOQRd",
        version: 300,
        opcode: FuncOpCode::FDOQRD,
        args: 0x06,
        function: predefined_functions::fdoqrd,
    },
    FunctionDefinition {
        name: "GetDrive",
        version: 300,
        opcode: FuncOpCode::GETDRIVE,
        args: 0x00,
        function: predefined_functions::getdrive,
    },
    FunctionDefinition {
        name: "SetDrive",
        version: 300,
        opcode: FuncOpCode::SETDRIVE,
        args: 0x01,
        function: predefined_functions::setdrive,
    },
    FunctionDefinition {
        name: "BS2I",
        version: 300,
        opcode: FuncOpCode::BS2I,
        args: 0x01,
        function: predefined_functions::bs2i,
    },
    FunctionDefinition {
        name: "BD2I",
        version: 300,
        opcode: FuncOpCode::BD2I,
        args: 0x01,
        function: predefined_functions::bd2i,
    },
    FunctionDefinition {
        name: "I2BS",
        version: 300,
        opcode: FuncOpCode::I2BS,
        args: 0x01,
        function: predefined_functions::i2bs,
    },
    FunctionDefinition {
        name: "I2BD",
        version: 300,
        opcode: FuncOpCode::I2BD,
        args: 0x01,
        function: predefined_functions::i2bd,
    },
    FunctionDefinition {
        name: "FTell",
        version: 300,
        opcode: FuncOpCode::FTELL,
        args: 0x01,
        function: predefined_functions::ftell,
    },
    FunctionDefinition {
        name: "OS",
        version: 300,
        opcode: FuncOpCode::OS,
        args: 0x00,
        function: predefined_functions::os,
    },
    FunctionDefinition {
        name: "ShortDesc",
        version: 340,
        opcode: FuncOpCode::SHORT_DESC,
        args: 0x00,
        function: predefined_functions::shortdesc,
    },
    FunctionDefinition {
        name: "GetBankBal",
        version: 340,
        opcode: FuncOpCode::GetBankBal,
        args: 0x02,
        function: predefined_functions::getbankbal,
    },
    FunctionDefinition {
        name: "GetMsgHdr",
        version: 340,
        opcode: FuncOpCode::GetMsgHdr,
        args: 0x03,
        function: predefined_functions::getmsghdr,
    },
    FunctionDefinition {
        name: "SetMsgHdr",
        version: 340,
        opcode: FuncOpCode::SetMsgHdr,
        args: 0x04,
        function: predefined_functions::setmsghdr,
    },
    // ALIASES
    FunctionDefinition {
        name: "ToString",
        version: 100,
        opcode: FuncOpCode::TOSTRING,
        args: 0x01,
        function: predefined_functions::tostring,
    },
    FunctionDefinition {
        name: "ToInt",
        version: 100,
        opcode: FuncOpCode::TOSWORD, // Note: This is correct it's not TOINTEGER for some reason.
        args: 0x01,
        function: predefined_functions::tosword,
    },
    FunctionDefinition {
        name: "ToDWord",
        version: 100,
        opcode: FuncOpCode::TOUNSIGNED,
        args: 0x01,
        function: predefined_functions::tounsigned,
    },
];

/*
#[test]
fn convert_definitions() {
    for def in &FUNCTION_DEFINITIONS {
        print!(
            "FunctionDefinition {{ name: \"{}\", opcode: FuncOpCode::{:?}, args: ",
            def.name, def.opcode
        );
        if def.args < 0 {
            print!("{}", def.args);
        } else {
            print!("0x{:02X}", def.args);
        }
        if def.args < 0 || def.args == 0x10 || def.args == 0x11 {
            print!(", function: predefined_functions::invalid");
        } else {
            print!(
                ", function: predefined_functions::{}",
                def.name.to_lowercase()
            );
        }
        println!(" }},");
    }
}*/
