use std::fmt::Display;

use crate::{vm::predefined_procedures, Res};

use super::VariableValue;

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum StatementSignature {
    Invalid,
    /// The first usize is the variable - 0 for none, second is the number of arguments
    ArgumentsWithVariable(usize, usize),

    /// The first i32 is a variable, 0 for none
    VariableArguments(usize),

    /// 3 arguments, first expression, after that a single i16 for the table number of a variable, third an expression
    SpecialCaseDlockg,

    /// 4 arguments, 3 expressions after that a single i16 for the table number of a variable
    SpecialCaseDcreate,

    /// 2 arguments, 2 single numbers for the table numbers of the arguments
    SpecialCaseSort,

    /// 2 arguments, 2 id expressions (2 i16 each)
    SpecialCaseVarSeg,

    /// n arguments, first 1 number for the number of arguments, followed by n table lookups
    SpecialCasePop,
}

#[repr(i16)]
#[allow(dead_code)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub enum OpCode {
    END = 1,
    CLS = 2,
    CLREOL = 3,
    MORE = 4,
    WAIT = 5,
    COLOR = 6,
    GOTO = 7,
    LET = 8,
    PRINT = 9,
    PRINTLN = 10,
    IFNOT = 11,
    CONFFLAG = 12,
    CONFUNFLAG = 13,
    DISPFILE = 14,
    INPUT = 15,
    FCREATE = 16,
    FOPEN = 17,
    FAPPEND = 18,
    FCLOSE = 19,
    FGET = 20,
    FPUT = 21,
    FPUTLN = 22,
    RESETDISP = 23,
    STARTDISP = 24,
    FPUTPAD = 25,
    HANGUP = 26,
    GETUSER = 27,
    PUTUSER = 28,
    DEFCOLOR = 29,
    DELETE = 30,
    DELUSER = 31,
    ADJTIME = 32,
    LOG = 33,
    INPUTSTR = 34,
    INPUTYN = 35,
    INPUTMONEY = 36,
    INPUTINT = 37,
    INPUTCC = 38,
    INPUTDATE = 39,
    INPUTTIME = 40,
    GOSUB = 41,
    RETURN = 42,
    PROMPTSTR = 43,
    DTRON = 44,
    DTROFF = 45,
    CDCHKON = 46,
    CDCHKOFF = 47,
    DELAY = 48,
    SENDMODEM = 49,
    INC = 50,
    DEC = 51,
    NEWLINE = 52,
    NEWLINES = 53,
    TOKENIZE = 54,
    GETTOKEN = 55,
    SHELL = 56,
    DISPTEXT = 57,
    STOP = 58,
    INPUTTEXT = 59,
    BEEP = 60,
    PUSH = 61,
    POP = 62,
    KBDSTUFF = 63,
    CALL = 64,
    JOIN = 65,
    QUEST = 66,
    BLT = 67,
    DIR = 68,
    KBDFILE = 69,
    BYE = 70,
    GOODBYE = 71,
    BROADCAST = 72,
    WAITFOR = 73,
    KBDCHKON = 74,
    KBDCHKOFF = 75,
    OPTEXT = 76,
    DISPSTR = 77,
    RDUNET = 78,
    WRUNET = 79,
    DOINTR = 80,
    VARSEG = 81,
    VAROFF = 82,
    POKEB = 83,
    POKEW = 84,
    VARADDR = 85,
    ANSIPOS = 86,
    BACKUP = 87,
    FORWARD = 88,
    FRESHLINE = 89,
    WRUSYS = 90,
    RDUSYS = 91,
    NEWPWD = 92,
    OPENCAP = 93,
    CLOSECAP = 94,
    MESSAGE = 95,
    SAVESCRN = 96,
    RESTSCRN = 97,
    SOUND = 98,
    CHAT = 99,
    SPRINT = 100,
    SPRINTLN = 101,
    MPRINT = 102,
    MPRINTLN = 103,
    RENAME = 104,
    FREWIND = 105,
    POKEDW = 106,
    DBGLEVEL = 107,
    SHOWON = 108,
    SHOWOFF = 109,
    PAGEON = 110,
    PAGEOFF = 111,
    FSEEK = 112,
    FFLUSH = 113,
    FREAD = 114,
    FWRITE = 115,
    FDEFIN = 116,
    FDEFOUT = 117,
    FDGET = 118,
    FDPUT = 119,
    FDPUTLN = 120,
    FDPUTPAD = 121,
    FDREAD = 122,
    FDWRITE = 123,
    ADJBYTES = 124,
    KBDSTRING = 125,
    ALIAS = 126,
    REDIM = 127,
    APPEND = 128,
    COPY = 129,
    KBDFLUSH = 130,
    MDMFLUSH = 131,
    KEYFLUSH = 132,
    LASTIN = 133,
    FLAG = 134,
    DOWNLOAD = 135,
    WRUSYSDOOR = 136,
    GETALTUSER = 137,
    ADJDBYTES = 138,
    ADJTBYTES = 139,
    ADJTFILES = 140,
    LANG = 141,
    SORT = 142,
    MOUSEREG = 143,
    SCRFILE = 144,
    SEARCHINIT = 145,
    SEARCHFIND = 146,
    SEARCHSTOP = 147,
    PRFOUND = 148,
    PRFOUNDLN = 149,
    TPAGET = 150,
    TPAPUT = 151,
    TPACGET = 152,
    TPACPUT = 153,
    TPAREAD = 154,
    TPAWRITE = 155,
    TPACREAD = 156,
    TPACWRITE = 157,
    BITSET = 158,
    BITCLEAR = 159,
    BRAG = 160,
    FREALTUSER = 161,
    SETLMR = 162,
    SETENV = 163,
    FCLOSEALL = 164,
    DECLARE = 165,
    FUNCTION = 166,
    PROCEDURE = 167,
    PCALL = 168,
    FPCLR = 169,
    BEGIN = 170,
    FEND = 171,
    STATIC = 172,
    STACKABORT = 173,
    DCREATE = 174,
    DOPEN = 175,
    DCLOSE = 176,
    DSETALIAS = 177,
    DPACK = 178,
    DCLOSEALL = 179,
    DLOCK = 180,
    DLOCKR = 181,
    DLOCKG = 182,
    DUNLOCK = 183,
    DNCREATE = 184,
    DNOPEN = 185,
    DNCLOSE = 186,
    DNCLOSEALL = 187,
    DNEW = 188,
    DADD = 189,
    DAPPEND = 190,
    DTOP = 191,
    DGO = 192,
    DBOTTOM = 193,
    DSKIP = 194,
    DBLANK = 195,
    DDELETE = 196,
    DRECALL = 197,
    DTAG = 198,
    DSEEK = 199,
    DFBLANK = 200,
    DGET = 201,
    DPUT = 202,
    DFCOPY = 203,

    EVAL = 204,
    ACCOUNT = 205,
    RECORDUSAGE = 206,
    MSGTOFILE = 207,
    QWKLIMITS = 208,
    COMMAND = 209,
    USELMRS = 210,
    CONFINFO = 211,
    ADJTUBYTES = 212,
    GRAFMODE = 213,
    ADDUSER = 214,
    KILLMSG = 215,
    CHDIR = 216,
    MKDIR = 217,
    REDIR = 218,
    FDOWRAKA = 219,
    FDOADDAKA = 220,
    FDOWRORG = 221,
    FDOADDORG = 222,
    FDOQMOD = 223,
    FDOQADD = 224,
    FDOQDEL = 225,
    SOUNDDELAY = 226,
    ShortDesc = 227,
    MoveMsg = 228,
    SetBankBal = 229,
}
pub const LAST_STMT: i16 = OpCode::SetBankBal as i16;

impl OpCode {
    pub fn get_definition(self) -> &'static StatementDefinition {
        &STATEMENT_DEFINITIONS[self as usize]
    }
}

impl Display for OpCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{self:?}")
    }
}

type PredefProc = fn(vm: &mut crate::vm::VirtualMachine, params: &mut [VariableValue]) -> Res<()>;

#[derive(Debug, PartialEq)]
pub struct StatementDefinition {
    pub name: &'static str,
    pub version: u16,
    pub opcode: OpCode,
    pub sig: StatementSignature,
    pub function: PredefProc,
}
impl StatementDefinition {
    pub(crate) fn get_statement_definition(
        identifier: &unicase::Ascii<String>,
    ) -> Option<&'static StatementDefinition> {
        STATEMENT_DEFINITIONS
            .iter()
            .find(|def| unicase::Ascii::new(def.name) == identifier)
    }
}

// Missing:
// "LAST IN" == "LASTIN"
// "WAIT FOR" == "WAITFOR"
// "GO SUB"
// " GO TO"
pub static STATEMENT_DEFINITIONS: [StatementDefinition; 234] = [
    StatementDefinition {
        // helps to map opcode to array index.
        name: "Placeholder",
        version: 100,
        opcode: OpCode::END,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::end,
    },
    StatementDefinition {
        name: "END",
        version: 100,
        opcode: OpCode::END,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::end,
    },
    StatementDefinition {
        name: "Cls",
        version: 100,
        opcode: OpCode::CLS,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::cls,
    },
    StatementDefinition {
        name: "ClrEOL",
        version: 100,
        opcode: OpCode::CLREOL,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::clreol,
    },
    StatementDefinition {
        name: "More",
        version: 100,
        opcode: OpCode::MORE,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::more,
    },
    StatementDefinition {
        name: "Wait",
        version: 100,
        opcode: OpCode::WAIT,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::wait,
    },
    StatementDefinition {
        name: "Color",
        version: 100,
        opcode: OpCode::COLOR,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::color,
    },
    StatementDefinition {
        name: "GOTO",
        version: 100,
        opcode: OpCode::GOTO,
        sig: StatementSignature::Invalid,
        function: predefined_procedures::invalid,
    },
    StatementDefinition {
        name: "LET",
        version: 100,
        opcode: OpCode::LET,
        sig: StatementSignature::ArgumentsWithVariable(1, 2),
        function: predefined_procedures::invalid,
    },
    StatementDefinition {
        name: "Print",
        version: 100,
        opcode: OpCode::PRINT,
        sig: StatementSignature::VariableArguments(0),
        function: predefined_procedures::print,
    },
    StatementDefinition {
        name: "PrintLn",
        version: 100,
        opcode: OpCode::PRINTLN,
        sig: StatementSignature::VariableArguments(0),
        function: predefined_procedures::println,
    },
    StatementDefinition {
        name: "IF",
        version: 100,
        opcode: OpCode::IFNOT,
        sig: StatementSignature::Invalid,
        function: predefined_procedures::invalid,
    },
    StatementDefinition {
        name: "ConfFlag",
        version: 100,
        opcode: OpCode::CONFFLAG,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::confflag,
    },
    StatementDefinition {
        name: "ConfUnflag",
        version: 100,
        opcode: OpCode::CONFUNFLAG,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::confunflag,
    },
    StatementDefinition {
        name: "DispFile",
        version: 100,
        opcode: OpCode::DISPFILE,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::dispfile,
    },
    StatementDefinition {
        name: "Input",
        version: 100,
        opcode: OpCode::INPUT,
        sig: StatementSignature::ArgumentsWithVariable(2, 2),
        function: predefined_procedures::input,
    },
    StatementDefinition {
        name: "FCreate",
        version: 100,
        opcode: OpCode::FCREATE,
        sig: StatementSignature::ArgumentsWithVariable(0, 4),
        function: predefined_procedures::fcreate,
    },
    StatementDefinition {
        name: "FOpen",
        version: 100,
        opcode: OpCode::FOPEN,
        sig: StatementSignature::ArgumentsWithVariable(0, 4),
        function: predefined_procedures::fopen,
    },
    StatementDefinition {
        name: "FAppend",
        version: 100,
        opcode: OpCode::FAPPEND,
        sig: StatementSignature::ArgumentsWithVariable(0, 4),
        function: predefined_procedures::fappend,
    },
    StatementDefinition {
        name: "FClose",
        version: 100,
        opcode: OpCode::FCLOSE,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::fclose,
    },
    StatementDefinition {
        name: "FGet",
        version: 100,
        opcode: OpCode::FGET,
        sig: StatementSignature::ArgumentsWithVariable(2, 2),
        function: predefined_procedures::fget,
    },
    StatementDefinition {
        name: "FPut",
        version: 100,
        opcode: OpCode::FPUT,
        sig: StatementSignature::VariableArguments(0),
        function: predefined_procedures::fput,
    },
    StatementDefinition {
        name: "FPutLn",
        version: 100,
        opcode: OpCode::FPUTLN,
        sig: StatementSignature::VariableArguments(0),
        function: predefined_procedures::fputln,
    },
    StatementDefinition {
        name: "ResetDisp",
        version: 100,
        opcode: OpCode::RESETDISP,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::resetdisp,
    },
    StatementDefinition {
        name: "StartDisp",
        version: 100,
        opcode: OpCode::STARTDISP,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::startdisp,
    },
    StatementDefinition {
        name: "FPutPad",
        version: 100,
        opcode: OpCode::FPUTPAD,
        sig: StatementSignature::ArgumentsWithVariable(0, 3),
        function: predefined_procedures::fputpad,
    },
    StatementDefinition {
        name: "Hangup",
        version: 100,
        opcode: OpCode::HANGUP,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::hangup,
    },
    StatementDefinition {
        name: "GetUser",
        version: 100,
        opcode: OpCode::GETUSER,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::getuser,
    },
    StatementDefinition {
        name: "PutUser",
        version: 100,
        opcode: OpCode::PUTUSER,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::putuser,
    },
    StatementDefinition {
        name: "DefColor",
        version: 100,
        opcode: OpCode::DEFCOLOR,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::defcolor,
    },
    StatementDefinition {
        name: "Delete",
        version: 100,
        opcode: OpCode::DELETE,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::delete,
    },
    StatementDefinition {
        name: "DelUser",
        version: 100,
        opcode: OpCode::DELUSER,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::deluser,
    },
    StatementDefinition {
        name: "AdjTime",
        version: 100,
        opcode: OpCode::ADJTIME,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::adjtime,
    },
    StatementDefinition {
        name: "Log",
        version: 100,
        opcode: OpCode::LOG,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::log,
    },
    StatementDefinition {
        name: "InputStr",
        version: 100,
        opcode: OpCode::INPUTSTR,
        sig: StatementSignature::ArgumentsWithVariable(2, 6),
        function: predefined_procedures::inputstr,
    },
    StatementDefinition {
        name: "InputYN",
        version: 100,
        opcode: OpCode::INPUTYN,
        sig: StatementSignature::ArgumentsWithVariable(2, 3),
        function: predefined_procedures::inputyn,
    },
    StatementDefinition {
        name: "InputMoney",
        version: 100,
        opcode: OpCode::INPUTMONEY,
        sig: StatementSignature::ArgumentsWithVariable(2, 3),
        function: predefined_procedures::inputmoney,
    },
    StatementDefinition {
        name: "InputInt",
        version: 100,
        opcode: OpCode::INPUTINT,
        sig: StatementSignature::ArgumentsWithVariable(2, 3),
        function: predefined_procedures::inputint,
    },
    StatementDefinition {
        name: "InputCC",
        version: 100,
        opcode: OpCode::INPUTCC,
        sig: StatementSignature::ArgumentsWithVariable(2, 3),
        function: predefined_procedures::inputcc,
    },
    StatementDefinition {
        name: "InputDate",
        version: 100,
        opcode: OpCode::INPUTDATE,
        sig: StatementSignature::ArgumentsWithVariable(2, 3),
        function: predefined_procedures::inputdate,
    },
    StatementDefinition {
        name: "InputTime",
        version: 100,
        opcode: OpCode::INPUTTIME,
        sig: StatementSignature::ArgumentsWithVariable(2, 3),
        function: predefined_procedures::inputtime,
    },
    StatementDefinition {
        name: "GOSUB",
        version: 100,
        opcode: OpCode::GOSUB,
        sig: StatementSignature::Invalid,
        function: predefined_procedures::invalid,
    },
    StatementDefinition {
        name: "RETURN",
        version: 100,
        opcode: OpCode::RETURN,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::invalid,
    },
    StatementDefinition {
        name: "PromptStr",
        version: 100,
        opcode: OpCode::PROMPTSTR,
        sig: StatementSignature::ArgumentsWithVariable(2, 5),
        function: predefined_procedures::promptstr,
    },
    StatementDefinition {
        name: "DtrOn",
        version: 100,
        opcode: OpCode::DTRON,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::dtron,
    },
    StatementDefinition {
        name: "DtrOff",
        version: 100,
        opcode: OpCode::DTROFF,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::dtroff,
    },
    StatementDefinition {
        name: "CdchkOn",
        version: 100,
        opcode: OpCode::CDCHKON,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::cdchkon,
    },
    StatementDefinition {
        name: "CdchkOff",
        version: 100,
        opcode: OpCode::CDCHKOFF,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::cdchkoff,
    },
    StatementDefinition {
        name: "Delay",
        version: 100,
        opcode: OpCode::DELAY,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::delay,
    },
    StatementDefinition {
        name: "SendModem",
        version: 100,
        opcode: OpCode::SENDMODEM,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::sendmodem,
    },
    StatementDefinition {
        name: "Inc",
        version: 100,
        opcode: OpCode::INC,
        sig: StatementSignature::ArgumentsWithVariable(1, 1),
        function: predefined_procedures::inc,
    },
    StatementDefinition {
        name: "Dec",
        version: 100,
        opcode: OpCode::DEC,
        sig: StatementSignature::ArgumentsWithVariable(1, 1),
        function: predefined_procedures::dec,
    },
    StatementDefinition {
        name: "NewLine",
        version: 100,
        opcode: OpCode::NEWLINE,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::newline,
    },
    StatementDefinition {
        name: "NewLines",
        version: 100,
        opcode: OpCode::NEWLINES,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::newlines,
    },
    StatementDefinition {
        name: "Tokenize",
        version: 100,
        opcode: OpCode::TOKENIZE,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::tokenize,
    },
    StatementDefinition {
        name: "GetToken",
        version: 100,
        opcode: OpCode::GETTOKEN,
        sig: StatementSignature::ArgumentsWithVariable(1, 1),
        function: predefined_procedures::gettoken,
    },
    StatementDefinition {
        name: "Shell",
        version: 100,
        opcode: OpCode::SHELL,
        sig: StatementSignature::ArgumentsWithVariable(2, 4),
        function: predefined_procedures::shell,
    },
    StatementDefinition {
        name: "DispText",
        version: 100,
        opcode: OpCode::DISPTEXT,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::disptext,
    },
    StatementDefinition {
        name: "STOP",
        version: 100,
        opcode: OpCode::STOP,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::stop,
    },
    StatementDefinition {
        name: "InputText",
        version: 100,
        opcode: OpCode::INPUTTEXT,
        sig: StatementSignature::ArgumentsWithVariable(2, 4),
        function: predefined_procedures::inputtext,
    },
    StatementDefinition {
        name: "Beep",
        version: 100,
        opcode: OpCode::BEEP,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::beep,
    },
    StatementDefinition {
        name: "Push",
        version: 100,
        opcode: OpCode::PUSH,
        sig: StatementSignature::VariableArguments(0),
        function: predefined_procedures::push,
    },
    StatementDefinition {
        name: "Pop",
        version: 100,
        opcode: OpCode::POP,
        sig: StatementSignature::SpecialCasePop,
        function: predefined_procedures::pop,
    },
    StatementDefinition {
        name: "KbdStuff",
        version: 100,
        opcode: OpCode::KBDSTUFF,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::kbdstuff,
    },
    StatementDefinition {
        name: "Call",
        version: 100,
        opcode: OpCode::CALL,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::call,
    },
    StatementDefinition {
        name: "Join",
        version: 100,
        opcode: OpCode::JOIN,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::join,
    },
    StatementDefinition {
        name: "Quest",
        version: 100,
        opcode: OpCode::QUEST,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::quest,
    },
    StatementDefinition {
        name: "Blt",
        version: 100,
        opcode: OpCode::BLT,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::blt,
    },
    StatementDefinition {
        name: "Dir",
        version: 100,
        opcode: OpCode::DIR,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::dir,
    },
    StatementDefinition {
        name: "KbdFile",
        version: 100,
        opcode: OpCode::KBDFILE,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::kbdfile,
    },
    StatementDefinition {
        name: "Bye",
        version: 100,
        opcode: OpCode::BYE,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::bye,
    },
    StatementDefinition {
        name: "Goodbye",
        version: 100,
        opcode: OpCode::GOODBYE,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::goodbye,
    },
    StatementDefinition {
        name: "Broadcast",
        version: 100,
        opcode: OpCode::BROADCAST,
        sig: StatementSignature::ArgumentsWithVariable(0, 3),
        function: predefined_procedures::broadcast,
    },
    StatementDefinition {
        name: "WaitFor",
        version: 100,
        opcode: OpCode::WAITFOR,
        sig: StatementSignature::ArgumentsWithVariable(2, 3),
        function: predefined_procedures::waitfor,
    },
    StatementDefinition {
        name: "KbdchkOn",
        version: 100,
        opcode: OpCode::KBDCHKON,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::kbdchkon,
    },
    StatementDefinition {
        name: "KbdchkOff",
        version: 100,
        opcode: OpCode::KBDCHKOFF,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::kbdchkoff,
    },
    StatementDefinition {
        name: "OpText",
        version: 100,
        opcode: OpCode::OPTEXT,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::optext,
    },
    StatementDefinition {
        name: "DispStr",
        version: 100,
        opcode: OpCode::DISPSTR,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::dispstr,
    },
    StatementDefinition {
        name: "RDUnet",
        version: 100,
        opcode: OpCode::RDUNET,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::rdunet,
    },
    StatementDefinition {
        name: "WRUnet",
        version: 100,
        opcode: OpCode::WRUNET,
        sig: StatementSignature::ArgumentsWithVariable(0, 6),
        function: predefined_procedures::wrunet,
    },
    StatementDefinition {
        name: "DoIntr",
        version: 100,
        opcode: OpCode::DOINTR,
        sig: StatementSignature::ArgumentsWithVariable(0, 10),
        function: predefined_procedures::dointr,
    },
    StatementDefinition {
        name: "VarSeg",
        version: 100,
        opcode: OpCode::VARSEG,
        sig: StatementSignature::SpecialCaseVarSeg,
        function: predefined_procedures::varseg,
    },
    StatementDefinition {
        name: "VarOff",
        version: 100,
        opcode: OpCode::VAROFF,
        sig: StatementSignature::SpecialCaseVarSeg,
        function: predefined_procedures::varoff,
    },
    StatementDefinition {
        name: "PokeB",
        version: 100,
        opcode: OpCode::POKEB,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::pokeb,
    },
    StatementDefinition {
        name: "PokeW",
        version: 100,
        opcode: OpCode::POKEW,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::pokew,
    },
    StatementDefinition {
        name: "VarAddr",
        version: 100,
        opcode: OpCode::VARADDR,
        sig: StatementSignature::SpecialCaseVarSeg,
        function: predefined_procedures::varaddr,
    },
    StatementDefinition {
        name: "AnsiPos",
        version: 100,
        opcode: OpCode::ANSIPOS,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::ansipos,
    },
    StatementDefinition {
        name: "Backup",
        version: 100,
        opcode: OpCode::BACKUP,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::backup,
    },
    StatementDefinition {
        name: "Forward",
        version: 100,
        opcode: OpCode::FORWARD,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::forward,
    },
    StatementDefinition {
        name: "Freshline",
        version: 100,
        opcode: OpCode::FRESHLINE,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::freshline,
    },
    StatementDefinition {
        name: "WRUSys",
        version: 100,
        opcode: OpCode::WRUSYS,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::wrusys,
    },
    StatementDefinition {
        name: "RDUSys",
        version: 100,
        opcode: OpCode::RDUSYS,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::rdusys,
    },
    StatementDefinition {
        name: "NewPwd",
        version: 100,
        opcode: OpCode::NEWPWD,
        sig: StatementSignature::ArgumentsWithVariable(2, 2),
        function: predefined_procedures::newpwd,
    },
    StatementDefinition {
        name: "OpenCap",
        version: 100,
        opcode: OpCode::OPENCAP,
        sig: StatementSignature::ArgumentsWithVariable(2, 2),
        function: predefined_procedures::opencap,
    },
    StatementDefinition {
        name: "CloseCap",
        version: 100,
        opcode: OpCode::CLOSECAP,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::closecap,
    },
    StatementDefinition {
        name: "Message",
        version: 100,
        opcode: OpCode::MESSAGE,
        sig: StatementSignature::ArgumentsWithVariable(0, 9),
        function: predefined_procedures::message,
    },
    StatementDefinition {
        name: "SaveScrn",
        version: 100,
        opcode: OpCode::SAVESCRN,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::savescrn,
    },
    StatementDefinition {
        name: "RestScrn",
        version: 100,
        opcode: OpCode::RESTSCRN,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::restscrn,
    },
    StatementDefinition {
        name: "Sound",
        version: 100,
        opcode: OpCode::SOUND,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::sound,
    },
    StatementDefinition {
        name: "Chat",
        version: 100,
        opcode: OpCode::CHAT,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::chat,
    },
    StatementDefinition {
        name: "SPrint",
        version: 100,
        opcode: OpCode::SPRINT,
        sig: StatementSignature::VariableArguments(0),
        function: predefined_procedures::sprint,
    },
    StatementDefinition {
        name: "SPrintLN",
        version: 100,
        opcode: OpCode::SPRINTLN,
        sig: StatementSignature::VariableArguments(0),
        function: predefined_procedures::sprintln,
    },
    StatementDefinition {
        name: "MPrint",
        version: 100,
        opcode: OpCode::MPRINT,
        sig: StatementSignature::VariableArguments(0),
        function: predefined_procedures::mprint,
    },
    StatementDefinition {
        name: "MPrintLn",
        version: 100,
        opcode: OpCode::MPRINTLN,
        sig: StatementSignature::VariableArguments(0),
        function: predefined_procedures::mprintln,
    },
    StatementDefinition {
        name: "Rename",
        version: 100,
        opcode: OpCode::RENAME,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::rename,
    },
    StatementDefinition {
        name: "FRewind",
        version: 100,
        opcode: OpCode::FREWIND,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::frewind,
    },
    StatementDefinition {
        name: "PokeDW",
        version: 100,
        opcode: OpCode::POKEDW,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::pokedw,
    },
    StatementDefinition {
        name: "DbgLevel",
        version: 100,
        opcode: OpCode::DBGLEVEL,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::dbglevel,
    },
    StatementDefinition {
        name: "ShowOn",
        version: 100,
        opcode: OpCode::SHOWON,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::showon,
    },
    StatementDefinition {
        name: "ShowOff",
        version: 100,
        opcode: OpCode::SHOWOFF,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::showoff,
    },
    StatementDefinition {
        name: "PageOn",
        version: 100,
        opcode: OpCode::PAGEON,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::pageon,
    },
    StatementDefinition {
        name: "PageOFf",
        version: 100,
        opcode: OpCode::PAGEOFF,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::pageoff,
    },
    StatementDefinition {
        name: "FSeek",
        version: 200,
        opcode: OpCode::FSEEK,
        sig: StatementSignature::ArgumentsWithVariable(0, 3),
        function: predefined_procedures::fseek,
    },
    StatementDefinition {
        name: "FFlush",
        version: 200,
        opcode: OpCode::FFLUSH,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::fflush,
    },
    StatementDefinition {
        name: "FRead",
        version: 200,
        opcode: OpCode::FREAD,
        sig: StatementSignature::ArgumentsWithVariable(2, 3),
        function: predefined_procedures::fread,
    },
    StatementDefinition {
        name: "FWrite",
        version: 200,
        opcode: OpCode::FWRITE,
        sig: StatementSignature::ArgumentsWithVariable(0, 3),
        function: predefined_procedures::fwrite,
    },
    StatementDefinition {
        name: "FDefIn",
        version: 200,
        opcode: OpCode::FDEFIN,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::fdefin,
    },
    StatementDefinition {
        name: "FDefOut",
        version: 200,
        opcode: OpCode::FDEFOUT,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::fdefout,
    },
    StatementDefinition {
        name: "FDGet",
        version: 200,
        opcode: OpCode::FDGET,
        sig: StatementSignature::ArgumentsWithVariable(1, 1),
        function: predefined_procedures::fdget,
    },
    StatementDefinition {
        name: "FDPut",
        version: 200,
        opcode: OpCode::FDPUT,
        sig: StatementSignature::VariableArguments(0),
        function: predefined_procedures::fdput,
    },
    StatementDefinition {
        name: "FDPutLn",
        version: 200,
        opcode: OpCode::FDPUTLN,
        sig: StatementSignature::VariableArguments(0),
        function: predefined_procedures::fdputln,
    },
    StatementDefinition {
        name: "FDPutPad",
        version: 200,
        opcode: OpCode::FDPUTPAD,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::fdputpad,
    },
    StatementDefinition {
        name: "FDRead",
        version: 200,
        opcode: OpCode::FDREAD,
        sig: StatementSignature::ArgumentsWithVariable(1, 2),
        function: predefined_procedures::fdread,
    },
    StatementDefinition {
        name: "FDWrite",
        version: 200,
        opcode: OpCode::FDWRITE,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::fdwrite,
    },
    StatementDefinition {
        name: "AdjBytes",
        version: 200,
        opcode: OpCode::ADJBYTES,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::adjbytes,
    },
    StatementDefinition {
        name: "KbdString",
        version: 200,
        opcode: OpCode::KBDSTRING,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::kbdstring,
    },
    StatementDefinition {
        name: "Alias",
        version: 200,
        opcode: OpCode::ALIAS,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::alias,
    },
    StatementDefinition {
        name: "ReDim",
        version: 200,
        opcode: OpCode::REDIM,
        sig: StatementSignature::VariableArguments(1),
        function: predefined_procedures::redim,
    },
    StatementDefinition {
        name: "Append",
        version: 200,
        opcode: OpCode::APPEND,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::append,
    },
    StatementDefinition {
        name: "Copy",
        version: 200,
        opcode: OpCode::COPY,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::copy,
    },
    StatementDefinition {
        name: "KbdFlush",
        version: 200,
        opcode: OpCode::KBDFLUSH,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::kbdflush,
    },
    StatementDefinition {
        name: "MdmFlush",
        version: 200,
        opcode: OpCode::MDMFLUSH,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::mdmflush,
    },
    StatementDefinition {
        name: "KeyFlush",
        version: 200,
        opcode: OpCode::KEYFLUSH,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::keyflush,
    },
    StatementDefinition {
        name: "LastIn",
        version: 200,
        opcode: OpCode::LASTIN,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::lastin,
    },
    StatementDefinition {
        name: "Flag",
        version: 200,
        opcode: OpCode::FLAG,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::flag,
    },
    StatementDefinition {
        name: "Download",
        version: 200,
        opcode: OpCode::DOWNLOAD,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::download,
    },
    StatementDefinition {
        name: "WRUsysDoor",
        version: 200,
        opcode: OpCode::WRUSYSDOOR,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::wrusysdoor,
    },
    StatementDefinition {
        name: "GetAltUser",
        version: 200,
        opcode: OpCode::GETALTUSER,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::getaltuser,
    },
    StatementDefinition {
        name: "AdjDBytes",
        version: 200,
        opcode: OpCode::ADJDBYTES,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::adjdbytes,
    },
    StatementDefinition {
        name: "AdjTBytes",
        version: 200,
        opcode: OpCode::ADJTBYTES,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::adjtbytes,
    },
    StatementDefinition {
        name: "AdjTFiles",
        version: 200,
        opcode: OpCode::ADJTFILES,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::ayjtfiles,
    },
    StatementDefinition {
        name: "Lang",
        version: 200,
        opcode: OpCode::LANG,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::lang,
    },
    StatementDefinition {
        name: "Sort",
        version: 200,
        opcode: OpCode::SORT,
        sig: StatementSignature::SpecialCaseSort,
        function: predefined_procedures::sort,
    },
    StatementDefinition {
        name: "MouseReg",
        version: 200,
        opcode: OpCode::MOUSEREG,
        sig: StatementSignature::ArgumentsWithVariable(0, 10),
        function: predefined_procedures::mousereg,
    },
    StatementDefinition {
        name: "ScrFile",
        version: 200,
        opcode: OpCode::SCRFILE,
        sig: StatementSignature::SpecialCaseVarSeg,
        function: predefined_procedures::scrfile,
    },
    StatementDefinition {
        name: "SearchInit",
        version: 200,
        opcode: OpCode::SEARCHINIT,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::searchinit,
    },
    StatementDefinition {
        name: "SearchFind",
        version: 200,
        opcode: OpCode::SEARCHFIND,
        sig: StatementSignature::ArgumentsWithVariable(2, 2),
        function: predefined_procedures::searchfind,
    },
    StatementDefinition {
        name: "SearchStop",
        version: 200,
        opcode: OpCode::SEARCHSTOP,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::searchstop,
    },
    StatementDefinition {
        name: "PrFound",
        version: 200,
        opcode: OpCode::PRFOUND,
        sig: StatementSignature::VariableArguments(0),
        function: predefined_procedures::prfound,
    },
    StatementDefinition {
        name: "PrFoundLn",
        version: 200,
        opcode: OpCode::PRFOUNDLN,
        sig: StatementSignature::VariableArguments(0),
        function: predefined_procedures::prfoundln,
    },
    StatementDefinition {
        name: "TPAGet",
        version: 200,
        opcode: OpCode::TPAGET,
        sig: StatementSignature::ArgumentsWithVariable(2, 2),
        function: predefined_procedures::tpaget,
    },
    StatementDefinition {
        name: "TPAPut",
        version: 200,
        opcode: OpCode::TPAPUT,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::tpaput,
    },
    StatementDefinition {
        name: "TPACGea",
        version: 200,
        opcode: OpCode::TPACGET,
        sig: StatementSignature::ArgumentsWithVariable(2, 3),
        function: predefined_procedures::tpacgea,
    },
    StatementDefinition {
        name: "TPACPut",
        version: 200,
        opcode: OpCode::TPACPUT,
        sig: StatementSignature::ArgumentsWithVariable(0, 3),
        function: predefined_procedures::tpacput,
    },
    StatementDefinition {
        name: "TPARead",
        version: 200,
        opcode: OpCode::TPAREAD,
        sig: StatementSignature::ArgumentsWithVariable(2, 2),
        function: predefined_procedures::tparead,
    },
    StatementDefinition {
        name: "TPAWrite",
        version: 200,
        opcode: OpCode::TPAWRITE,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::tpawrite,
    },
    StatementDefinition {
        name: "TPACRead",
        version: 200,
        opcode: OpCode::TPACREAD,
        sig: StatementSignature::ArgumentsWithVariable(2, 3),
        function: predefined_procedures::tpacread,
    },
    StatementDefinition {
        name: "TPACWrite",
        version: 200,
        opcode: OpCode::TPACWRITE,
        sig: StatementSignature::ArgumentsWithVariable(0, 3),
        function: predefined_procedures::tpacwrite,
    },
    StatementDefinition {
        name: "BitSet",
        version: 200,
        opcode: OpCode::BITSET,
        sig: StatementSignature::ArgumentsWithVariable(1, 2),
        function: predefined_procedures::bitset,
    },
    StatementDefinition {
        name: "BitClear",
        version: 200,
        opcode: OpCode::BITCLEAR,
        sig: StatementSignature::ArgumentsWithVariable(1, 2),
        function: predefined_procedures::bitclear,
    },
    StatementDefinition {
        name: "Brag",
        version: 200,
        opcode: OpCode::BRAG,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::brag,
    },
    StatementDefinition {
        name: "FRealTUser",
        version: 200,
        opcode: OpCode::FREALTUSER,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::frealtuser,
    },
    StatementDefinition {
        name: "SetLMR",
        version: 200,
        opcode: OpCode::SETLMR,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::setlmr,
    },
    StatementDefinition {
        name: "SetEnv",
        version: 200,
        opcode: OpCode::SETENV,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::setenv,
    },
    StatementDefinition {
        name: "FCloseAll",
        version: 200,
        opcode: OpCode::FCLOSEALL,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::fcloseall,
    },
    StatementDefinition {
        name: "Declare",
        version: 200,
        opcode: OpCode::DECLARE,
        sig: StatementSignature::ArgumentsWithVariable(10, 10),
        function: predefined_procedures::invalid,
    },
    StatementDefinition {
        name: "Function",
        version: 200,
        opcode: OpCode::FUNCTION,
        sig: StatementSignature::ArgumentsWithVariable(10, 10),
        function: predefined_procedures::invalid,
    },
    StatementDefinition {
        name: "Procedure",
        version: 200,
        opcode: OpCode::PROCEDURE,
        sig: StatementSignature::ArgumentsWithVariable(10, 10),
        function: predefined_procedures::invalid,
    },
    StatementDefinition {
        name: "PCALL",
        version: 200,
        opcode: OpCode::PCALL,
        sig: StatementSignature::Invalid,
        function: predefined_procedures::invalid,
    },
    StatementDefinition {
        name: "FPCLR",
        version: 200,
        opcode: OpCode::FPCLR,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::invalid,
    },
    StatementDefinition {
        name: "Begin",
        version: 200,
        opcode: OpCode::BEGIN,
        sig: StatementSignature::ArgumentsWithVariable(10, 10),
        function: predefined_procedures::invalid,
    },
    StatementDefinition {
        name: "FEND",
        version: 200,
        opcode: OpCode::FEND,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::invalid,
    },
    StatementDefinition {
        name: "Static",
        version: 200,
        opcode: OpCode::STATIC,
        sig: StatementSignature::ArgumentsWithVariable(10, 10),
        function: predefined_procedures::invalid,
    },
    StatementDefinition {
        name: "StackAbort",
        version: 200,
        opcode: OpCode::STACKABORT,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::stackabort,
    },
    StatementDefinition {
        name: "DCreate",
        version: 300,
        opcode: OpCode::DCREATE,
        sig: StatementSignature::SpecialCaseDcreate,
        function: predefined_procedures::dcreate,
    },
    StatementDefinition {
        name: "DOpen",
        version: 300,
        opcode: OpCode::DOPEN,
        sig: StatementSignature::ArgumentsWithVariable(0, 3),
        function: predefined_procedures::dopen,
    },
    StatementDefinition {
        name: "DClose",
        version: 300,
        opcode: OpCode::DCLOSE,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::dclose,
    },
    StatementDefinition {
        name: "DSetAlias",
        version: 300,
        opcode: OpCode::DSETALIAS,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::dsetalias,
    },
    StatementDefinition {
        name: "DPack",
        version: 300,
        opcode: OpCode::DPACK,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::dpack,
    },
    StatementDefinition {
        name: "DCloseAll",
        version: 300,
        opcode: OpCode::DCLOSEALL,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::dcloseall,
    },
    StatementDefinition {
        name: "DLock",
        version: 300,
        opcode: OpCode::DLOCK,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::dlock,
    },
    StatementDefinition {
        name: "DLockR",
        version: 300,
        opcode: OpCode::DLOCKR,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::dlockr,
    },
    StatementDefinition {
        name: "DLockG",
        version: 300,
        opcode: OpCode::DLOCKG,
        sig: StatementSignature::SpecialCaseDlockg,
        function: predefined_procedures::dlockg,
    },
    StatementDefinition {
        name: "DUnlock",
        version: 300,
        opcode: OpCode::DUNLOCK,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::dunlock,
    },
    StatementDefinition {
        name: "DNCreate",
        version: 300,
        opcode: OpCode::DNCREATE,
        sig: StatementSignature::ArgumentsWithVariable(0, 3),
        function: predefined_procedures::dncreate,
    },
    StatementDefinition {
        name: "DNOpen",
        version: 300,
        opcode: OpCode::DNOPEN,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::dnopen,
    },
    StatementDefinition {
        name: "DNClose",
        version: 300,
        opcode: OpCode::DNCLOSE,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::dnclose,
    },
    StatementDefinition {
        name: "DNCloseAll",
        version: 300,
        opcode: OpCode::DNCLOSEALL,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::dncloseall,
    },
    StatementDefinition {
        name: "DNew",
        version: 300,
        opcode: OpCode::DNEW,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::dnew,
    },
    StatementDefinition {
        name: "DAdd",
        version: 300,
        opcode: OpCode::DADD,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::dadd,
    },
    StatementDefinition {
        name: "DAppend",
        version: 300,
        opcode: OpCode::DAPPEND,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::dappend,
    },
    StatementDefinition {
        name: "DTop",
        version: 300,
        opcode: OpCode::DTOP,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::dtop,
    },
    StatementDefinition {
        name: "DGo",
        version: 300,
        opcode: OpCode::DGO,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::dgo,
    },
    StatementDefinition {
        name: "DBottom",
        version: 300,
        opcode: OpCode::DBOTTOM,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::dbottom,
    },
    StatementDefinition {
        name: "DSkip",
        version: 300,
        opcode: OpCode::DSKIP,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::dskip,
    },
    StatementDefinition {
        name: "DBlank",
        version: 300,
        opcode: OpCode::DBLANK,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::dblank,
    },
    StatementDefinition {
        name: "DDelete",
        version: 300,
        opcode: OpCode::DDELETE,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::ddelete,
    },
    StatementDefinition {
        name: "DRecall",
        version: 300,
        opcode: OpCode::DRECALL,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::drecall,
    },
    StatementDefinition {
        name: "DTag",
        version: 300,
        opcode: OpCode::DTAG,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::dtag,
    },
    StatementDefinition {
        name: "DSeek",
        version: 300,
        opcode: OpCode::DSEEK,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::dseek,
    },
    StatementDefinition {
        name: "DFBlank",
        version: 300,
        opcode: OpCode::DFBLANK,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::dfblank,
    },
    StatementDefinition {
        name: "DGet",
        version: 300,
        opcode: OpCode::DGET,
        sig: StatementSignature::ArgumentsWithVariable(3, 3),
        function: predefined_procedures::dget,
    },
    StatementDefinition {
        name: "DPut",
        version: 300,
        opcode: OpCode::DPUT,
        sig: StatementSignature::ArgumentsWithVariable(0, 3),
        function: predefined_procedures::dput,
    },
    StatementDefinition {
        name: "DFCopy",
        version: 300,
        opcode: OpCode::DFCOPY,
        sig: StatementSignature::ArgumentsWithVariable(0, 4),
        function: predefined_procedures::dfcopy,
    },
    StatementDefinition {
        name: "Eval",
        version: 300,
        opcode: OpCode::EVAL,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::eval,
    },
    StatementDefinition {
        name: "Account",
        version: 300,
        opcode: OpCode::ACCOUNT,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::account,
    },
    StatementDefinition {
        name: "RecordUsage",
        version: 300,
        opcode: OpCode::RECORDUSAGE,
        sig: StatementSignature::ArgumentsWithVariable(0, 5),
        function: predefined_procedures::recordusage,
    },
    StatementDefinition {
        name: "MsgToFile",
        version: 300,
        opcode: OpCode::MSGTOFILE,
        sig: StatementSignature::ArgumentsWithVariable(0, 3),
        function: predefined_procedures::msgtofile,
    },
    StatementDefinition {
        name: "QwkLimits",
        version: 300,
        opcode: OpCode::QWKLIMITS,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::qwklimits,
    },
    StatementDefinition {
        name: "Command",
        version: 300,
        opcode: OpCode::COMMAND,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::command,
    },
    StatementDefinition {
        name: "USelMrs",
        version: 300,
        opcode: OpCode::USELMRS,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::uselmrs,
    },
    StatementDefinition {
        name: "ConfInfo",
        version: 300,
        opcode: OpCode::CONFINFO,
        sig: StatementSignature::ArgumentsWithVariable(0, 3),
        function: predefined_procedures::confinfo,
    },
    StatementDefinition {
        name: "AdjTUBytes",
        version: 300,
        opcode: OpCode::ADJTUBYTES,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::adjtubytes,
    },
    StatementDefinition {
        name: "GrafMode",
        version: 300,
        opcode: OpCode::GRAFMODE,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::grafmode,
    },
    StatementDefinition {
        name: "AddUser",
        version: 300,
        opcode: OpCode::ADDUSER,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::adduser,
    },
    StatementDefinition {
        name: "KillMsg",
        version: 300,
        opcode: OpCode::KILLMSG,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::killmsg,
    },
    StatementDefinition {
        name: "ChDir",
        version: 300,
        opcode: OpCode::CHDIR,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::chdir,
    },
    StatementDefinition {
        name: "MkDir",
        version: 300,
        opcode: OpCode::MKDIR,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::mkdir,
    },
    StatementDefinition {
        name: "ReDir",
        version: 300,
        opcode: OpCode::REDIR,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::redir,
    },
    StatementDefinition {
        name: "FDOWRAka",
        version: 300,
        opcode: OpCode::FDOWRAKA,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::fdowraka,
    },
    StatementDefinition {
        name: "FDOADDAka",
        version: 300,
        opcode: OpCode::FDOADDAKA,
        sig: StatementSignature::ArgumentsWithVariable(0, 3),
        function: predefined_procedures::fdoaddaka,
    },
    StatementDefinition {
        name: "FDOWROrg",
        version: 300,
        opcode: OpCode::FDOWRORG,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::fdowrorg,
    },
    StatementDefinition {
        name: "FDOADDOrg",
        version: 300,
        opcode: OpCode::FDOADDORG,
        sig: StatementSignature::ArgumentsWithVariable(0, 3),
        function: predefined_procedures::fdoaddorg,
    },
    StatementDefinition {
        name: "FDOQMod",
        version: 300,
        opcode: OpCode::FDOQMOD,
        sig: StatementSignature::ArgumentsWithVariable(0, 4),
        function: predefined_procedures::fdoqmod,
    },
    StatementDefinition {
        name: "FDOQAdd",
        version: 300,
        opcode: OpCode::FDOQADD,
        sig: StatementSignature::ArgumentsWithVariable(0, 3),
        function: predefined_procedures::fdoqadd,
    },
    StatementDefinition {
        name: "FDOQDel",
        version: 300,
        opcode: OpCode::FDOQDEL,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::fdoqdel,
    },
    StatementDefinition {
        name: "SoundDelay",
        version: 300,
        opcode: OpCode::SOUNDDELAY,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::sounddelay,
    },
    // 3.4 statements
    StatementDefinition {
        name: "ShortDesc",
        version: 340,
        opcode: OpCode::ShortDesc,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::sounddelay,
    },
    StatementDefinition {
        name: "MoveMsg",
        version: 340,
        opcode: OpCode::MoveMsg,
        sig: StatementSignature::ArgumentsWithVariable(0, 3),
        function: predefined_procedures::sounddelay,
    },
    StatementDefinition {
        name: "SetBankBal",
        version: 340,
        opcode: OpCode::SetBankBal,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::sounddelay,
    },
    // Alias section
    // Moving to the end, so that the opcode <--> index mapping is not broken
    StatementDefinition {
        name: "DLockF",
        version: 300,
        opcode: OpCode::DLOCK,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::dlock,
    },
    StatementDefinition {
        name: "PutAltUser",
        version: 100,
        opcode: OpCode::PUTUSER,
        sig: StatementSignature::ArgumentsWithVariable(0, 0),
        function: predefined_procedures::putuser,
    },
    StatementDefinition {
        name: "Erase",
        version: 100,
        opcode: OpCode::DELETE,
        sig: StatementSignature::ArgumentsWithVariable(0, 1),
        function: predefined_procedures::delete,
    },
    StatementDefinition {
        name: "Poke",
        version: 100,
        opcode: OpCode::POKEB,
        sig: StatementSignature::ArgumentsWithVariable(0, 2),
        function: predefined_procedures::pokeb,
    },
];

#[test]
fn check_table_consistency() {
    for def in &STATEMENT_DEFINITIONS {
        assert!(
            def.opcode == STATEMENT_DEFINITIONS[def.opcode as usize].opcode,
            "Opcode table mismatch: {:?}/{} was '{}':{:?}",
            def.opcode,
            def.opcode as usize,
            STATEMENT_DEFINITIONS[def.opcode as usize].name,
            STATEMENT_DEFINITIONS[def.opcode as usize].opcode
        );
    }
}

/*
#[test]
fn convert_definitions() {
    for def in &STATEMENT_DEFINITIONS {
        if def.opcode as usize >= STATEMENT_SIGNATURE_TABLE.len() {
            break;
        }
        print!("StatementDefinition {{ name: \"{}\", version:100, opcode: OpCode::{}, sig:", def.name, def.opcode);
        let sig = STATEMENT_SIGNATURE_TABLE[def.opcode as usize];
        match sig {
            0 => print!("StatementSignature::ArgumentsWithVariable(0, 0)"),
            1..=0xF => print!("StatementSignature::ArgumentsWithVariable(0, {})", sig),
            0x11..=0x1F => print!("StatementSignature::ArgumentsWithVariable(1, {})", sig - 0x10),
            0x21..=0x2F => print!("StatementSignature::ArgumentsWithVariable(2, {})", sig - 0x20),
            0xF6 => print!("StatementSignature::SpecialCaseProcedure"),
            0xF7 => print!("StatementSignature::SpecialCaseDLockG"),
            0xF8 => print!("StatementSignature::SpecialCaseDCreate"),
            0xF9 => print!("StatementSignature::SpecialCaseSort"),
            0xFA => print!("StatementSignature::VariableArguments(1)"),
            0xFD => print!("StatementSignature::Label"),
            0xFE => print!("StatementSignature::VariableArguments(0)"),
            0xFF => print!("StatementSignature::SpecialCaseIfWhen"),
            _ => {
                let max = (STATEMENT_SIGNATURE_TABLE[def.opcode as usize] & 0xf0) * 16 + (STATEMENT_SIGNATURE_TABLE[def.opcode as usize] & 0x0f);
                let argument = max & 0xFF;
                let variable = max / 256;
                print!("StatementSignature::ArgumentsWithVariable({}, {})", argument, variable);
            }
        }
        print!(", function: predefined_procedures::{}", def.name.to_lowercase());


        print!("}},\n");
    }
}*/
