use crate::ast::*;

// Statement Variable-Types, 0 = none / aa = not defined
//				 1- f= number of exp
//				11-1f= number of exp, exp 1 is a var
//              21-2f= number of exp, exp 2 is a var
//              0xf6 = special case procedure
//              0xf7 = special case dlockg
//              0xf8 = special case dcreate
//              0xf9 = special case sort
//				0xfa = varies exp, exp 1 is a var (redim)
//              0xfc = varies var (pop)
//              0xfd = label (goto)
//			    0xfe = varies exp (println)
//			    0xff = special case if
pub const STATEMENT_SIGNATURE_TABLE: [i32; 227] = [
    0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0xfd, //0
    0x12, 0xfe, 0xfe, 0xff, 0x02, 0x02, 0x02, 0x22,
    0x04, 0x04, 0x04, 0x01, 0x22, 0xfe, 0xfe, 0x00, //1
    0x01, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00,
    0x01, 0x02, 0x26, 0x23, 0x23, 0x23, 0x23, 0x23, //2
    0x23, 0xfd, 0x00, 0x25, 0x00, 0x00, 0x00, 0x00,
    0x01, 0x01, 0x11, 0x11, 0x00, 0x01, 0x01, 0x11, //3
    0x24, 0x02, 0x00, 0x24, 0x00, 0xfe, 0xfc, 0x01,
    0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, //4
    0x03, 0x23, 0x00, 0x00, 0x01, 0x01, 0x01, 0x06,
    0x0a, 0xf2, 0xf2, 0x02, 0x02, 0xf2, 0x02, 0x01, //5
    0x01, 0x00, 0x00, 0x00, 0x22, 0x22, 0x00, 0x09,
    0x00, 0x00, 0x01, 0x00, 0xfe, 0xfe, 0xfe, 0xfe, //6
    0x02, 0x01, 0x02, 0x01, 0x00, 0x00, 0x00, 0x00,
    0x03, 0x01, 0x23, 0x03, 0x01, 0x01, 0x11, 0xfe, //7
    0xfe, 0x02, 0x12, 0x02, 0x01, 0x01, 0x01, 0xfa,
    0x02, 0x02, 0x00, 0x00, 0x00, 0x01, 0x01, 0x01, //8
    0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0xf9, 0x0a,
    0xf2, 0x02, 0x22, 0x00, 0xfe, 0xfe, 0x22, 0x02, //9
    0x23, 0x03, 0x22, 0x02, 0x23, 0x03, 0x12, 0x12,
    0x00, 0x00, 0x02, 0x01, 0x00, 0xaa, 0xaa, 0xaa, //A
    0xf6, 0x00, 0xaa, 0x00, 0xaa, 0x01, 0xf8, 0x03,
    0x01, 0x02, 0x01, 0x00, 0x01, 0x02, 0xf7, 0x01, //B
    0x03, 0x02, 0x02, 0x01, 0x01, 0x01, 0x01, 0x01,
    0x02, 0x01, 0x02, 0x01, 0x01, 0x01, 0x02, 0x02, //C
    0x02, 0x33, 0x03, 0x04, 0x01, 0x02, 0x05, 0x03,
    0x02, 0x02, 0x01, 0x03, 0x01, 0x01, 0x02, 0x02, //D
    0x01, 0x01, 0x01, 0x02, 0x03, 0x02, 0x03, 0x04,
    0x03, 0x01, 0x02                           //E
];

// Funktions Variable-Types, 0 = no exp / aa = not defined
//			     1- f= numbers of exp using ()
//              0x10 = only rvalue (!)
//			    0x11 = lvalue rvalue (+,-,...)
pub const FUNCTION_SIGNATURE_TABLE: [i32; 286] = [
    0xaa, 0x10, 0x10, 0x11, 0x11, 0x11, 0x11, 0x11,
    0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x10, //F
    0x11, 0x11, 0xaa, 0x01, 0x01, 0x01, 0x03, 0x02,
    0x02, 0x01, 0x01, 0x01, 0x01, 0x02, 0x00, 0x02, //E
    0x02, 0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, //D
    0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
    0x00, 0x00, 0x00, 0x01, 0x03, 0x02, 0x00, 0x01, //C
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x00, 0x02, //B
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, //A
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x01, //9
    0x01, 0x02, 0x01, 0x02, 0x02, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x01, 0x01, 0x01, 0x00, 0x00, 0x02, //8
    0x02, 0x02, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00,
    0x01, 0x00, 0x01, 0x02, 0x00, 0x03, 0x00, 0x00, //7
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x01, 0x02, 0x01, 0x00, 0x04, 0x00, //6
    0x00, 0x03, 0x02, 0x01, 0x01, 0x01, 0x01, 0x01,
    0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, //5
    0x01, 0x01, 0x00, 0x01, 0x01, 0x01, 0x01, 0x01,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, //4
    0x00, 0x00, 0x01, 0x00, 0x02, 0x03, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, //3
    0x02, 0x01, 0x00, 0x00, 0x00, 0x01, 0x01, 0x01,
    0x02, 0x01, 0x01, 0x01, 0x01, 0x02, 0x02, 0x01, //2
    0x01, 0x02, 0x00, 0x00, 0x01, 0x00, 0x03, 0x01,
    0x02, 0x01, 0x01, 0x01, 0x02, 0x01, 0x02, 0x02, //1
    0x01, 0x01, 0x01, 0x01, 0x01, 0x02, 0x01, 0x02,
    0x01, 0x01, 0x01, 0x02, 0x02, 0x02, 0x02, 0x03, //0
    0x04, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x04,
    0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x02, 0x01, //F
    0x00, 0x02, 0x01, 0x01, 0x01, 0x06, 0x00, 0x01,
    0x01, 0x01, 0x01, 0x01, 0x01, 0x00            //E
];

pub const TYPE_NAMES: [VariableType; 18] = [
    VariableType::Boolean,
    VariableType::Unsigned,
    VariableType::Date,
    VariableType::EDate,
    VariableType::Integer,
    VariableType::Money,
    VariableType::Real,
    VariableType::String,
    VariableType::Time,
    VariableType::Byte,
    VariableType::Word,
    VariableType::SByte,
    VariableType::SWord,
    VariableType::BigStr,
    VariableType::Real,
    VariableType::Unknown,
    VariableType::Unknown,
    VariableType::DDate
];


pub const CONSTANT_2_OFFSETS: [i32; 18] = [
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
    0x10, 0x11
];
pub const CONSTANT_2_NAMES: [Constant; 18] = [
    Constant::START_BAL,
    Constant::START_SESSION,
    Constant::DEB_CALL,
    Constant::DEB_TIME,
    Constant::DEB_MSGREAD,
    Constant::DEB_MSGCAP,
    Constant::DEB_MSGWRITE,
    Constant::DEB_MSGECHOED,
    Constant::DEB_MSGPRIVATE,
    Constant::DEB_DOWNFILE,
    Constant::DEB_DOWNBYTES,
    Constant::DEB_CHAT,
    Constant::DEB_TPU,
    Constant::DEB_SPECIAL,
    Constant::CRED_UPFILE,
    Constant::CRED_UPBYTES,
    Constant::CRED_SPECIAL,
    Constant::SEC_DROP
];

pub const CONSTANT_CONFERENCE_OFFSETS: [i32; 6] = [0x02, 0x10, 0x01, 0x04, 0x08, -1];
pub const CONSTANT_CONFERENCE_NAMES: [Constant; 5] = [Constant::F_EXP, Constant::F_MW, Constant::F_REG, Constant::F_SEL, Constant::F_SYS];

pub const CONSTANT_NAMES_OFFSETS: [i32; 5] = [0, 1, 4, 2, -1];
pub const CONSTANT_NAMES_DISPLAY: [Constant; 4] = [Constant::DEFS, Constant::GRAPH, Constant::LANG, Constant::SEC];

pub const CONSTANT_FACCESS_OFFSETS: [i32; 4] = [0, 2, 1, -1];
pub const CONSTANT_FACCESS_NAMES: [Constant; 3] = [Constant::O_RD, Constant::O_RW, Constant::O_WR];

pub const CONSTANT_SEEK_OFFSETS: [i32; 4] = [1, 2, 0, -1];
pub const CONSTANT_SEEK_NAMES: [Constant; 3] = [Constant::SEEK_CUR, Constant::SEEK_END, Constant::SEEK_SET];

pub const CONSTANT_OPENFLAGS_OFFSETS: [i32; 5] = [3, 0, 1, 2, -1];
pub const CONSTANT_OPENFLAGS_NAMES: [Constant; 4] = [Constant::S_DB, Constant::S_DN, Constant::S_DR, Constant::S_DW];

pub const CONSTANT_1_OFFSETS: [i32; 19] = [
    0x2000,
    0x0800,
    0x0000,
    0x0001,
    0x0020,
    0x0002,
    0x0004,
    0x1000,
    0x0100,
    0x0080,
    0x8000,
    0x10000,
    0x0040,
    0x0400,
    0x0010,
    0x0008,
    0x0200,
    0x4000,
    -1
];
pub const CONSTANT_1_NAMES: [Constant; 18] = [
    Constant::AUTO,
    Constant::BELL,
    Constant::DEFS,
    Constant::ECHODOTS,
    Constant::ERASELINE,
    Constant::FIELDLEN,
    Constant::GUIDE,
    Constant::HIGHASCII,
    Constant::LFAFTER,
    Constant::LFBEFORE,
    Constant::LOGIT,
    Constant::LOGITLEFT,
    Constant::NEWLINE,
    Constant::NOCLEAR,
    Constant::STACKED,
    Constant::UPCASE,
    Constant::WORDWRAP,
    Constant::YESNO
];

pub const CONSTANT_LINECOUNT_OFFSETS: [i32; 4] = [2, 1, 0, -1];
pub const CONSTANT_LINECOUNT_NAMES: [Constant; 3] = [Constant::FCL, Constant::FNS, Constant::NC];

pub const BIN_EXPR: [BinOp; 18] = [
    BinOp::Add, // UPLUS
    BinOp::Add, // UPLUS
    BinOp::Sub, // UMINUS
    BinOp::PoW,
    BinOp::Mul, // 5
    BinOp::Div,
    BinOp::Mod,
    BinOp::Add,
    BinOp::Sub,
    BinOp::Eq, // 10
    BinOp::NotEq,
    BinOp::Lower,
    BinOp::LowerEq,
    BinOp::Greater,
    BinOp::GreaterEq,
    BinOp::Add, // NOT token
    BinOp::And,
    BinOp::Or // 18
];

pub const EXPR_NAMES: [&str; 286] = [
    "???", "+", "-", "^", "*", "/", "%", "+", "-", "=", "<>", "<", "<=",
    ">", ">=", "!", "&", "|", "???", "LEN", "LOWER", "UPPER", "MID",
    "LEFT", "RIGHT", "SPACE", "FERR", "CHR", "ASC", "INSTR",
    "ABORT", "LTRIM", "RTRIM", "TRIM", "RANDOM", "DATE", "TIME",
    "U_NAME", "U_LDATE", "U_LTIME", "U_LDIR", "U_LOGONS",
    "U_FUL", "U_FDL", "U_BDLDAY", "U_TIMEON", "U_BDL", "U_BUL",
    "YEAR", "MONTH", "DAY", "DOW", "HOUR", "MIN", "SEC",
    "TIMEAP", "VER", "NOCHAR", "YESCHAR", "STRIPATX",
    "REPLACE", "STRIP", "INKEY", "STRING", "MASK_PWD",
    "MASK_ALPHA", "MASK_NUM", "MASK_ALNUM", "MASK_FILE",
    "MASK_PATH", "MASK_ASCII", "CURCONF", "PCBDAT", "PPEPATH",
    "VALDATE", "VALTIME", "U_MSGRD", "U_MSGWR", "PCBNODE",
    "READLINE", "SYSOPSEC", "ONLOCAL", "UN_STAT", "UN_NAME",
    "UN_CITY", "UN_OPER", "CURSEC", "GETTOKEN", "MINLEFT",
    "MINON", "GETENV", "CALLID", "REGAL", "REGAH", "REGBL",
    "REGBH", "REGCL", "REGCH", "REGDL", "REGDH", "REGAX",
    "REGBX", "REGCX", "REGDX", "REGSI", "REGDI", "REGF",
    "REGCF", "REGDS", "REGES", "B2W", "PEEKB", "PEEKW",
    "MKADDR", "EXIST", "I2S", "S2I", "CARRIER", "TOKENSTR",
    "CDON", "LANGEXT", "ANSION", "VALCC", "FMTCC", "CCTYPE",
    "GETX", "GETY", "AND", "OR", "XOR", "NOT", "U_PWDHIST",
    "U_PWDLC", "U_PWDTC", "U_STAT", "DEFCOLOR", "ABS",
    "GRAFMODE", "PSA", "FILEINF", "PPENAME", "MKDATE",
    "CURCOLOR", "KINKEY", "MINKEY", "MAXNODE", "SLPATH",
    "HELPPATH", "TEMPPATH", "MODEM", "LOGGEDON", "CALLNUM",
    "MGETBYTE", "TOKCOUNT", "U_RECNUM", "U_INCONF", "PEEKDW",
    "DBGLEVEL", "SCRTEXT", "SHOWSTAT", "PAGESTAT",
    "REPLACESTR", "STRIPSTR", "TOBIGSTR", "TOBOOLEAN",
    "TOBYTE", "TODATE", "TODREAL", "TOEDATE", "TOINTEGER",
    "TOMONEY", "TOREAL", "TOSBYTE", "TOSWORD", "TOTIME",
    "TOUNSIGNED", "TOWORD", "MIXED", "ALIAS", "CONFREG",
    "CONFEXP", "CONFSEL", "CONFSYS", "CONFMW", "LPRINTED",
    "ISNONSTOP", "ERRCORRECT", "CONFALIAS", "USERALIAS",
    "CURUSER", "U_LMR", "CHATSTAT", "DEFANS", "LASTANS",
    "MEGANUM", "EVTTIMEADJ", "ISBITSET", "FMTREAL", "FLAGCNT",
    "KBDBUFSIZE", "PPLBUFSIZE", "KBDFILUSED", "LOMSGNUM",
    "HIMSGNUM", "DRIVESPACE", "OUTBYTES", "HICONFNUM",
    "INBYTES", "CRC32", "PCBMAC", "ACTMSGNUM", "STACKLEFT",
    "STACKERR", "DGETALIAS", "DBOF", "DCHANGED", "DDECIMALS",
    "DDELETED", "DEOF", "DERR", "DFIELDS", "DLENGTH", "DNAME",
    "DRECCOUNT", "DRECNO", "DTYPE", "FNEXT", "DNEXT", "TODDATE",
    "DCLOSEALL", "DOPEN", "DCLOSE", "DSETALIAS", "DPACK",
    "DLOCKF", "DLOCK", "DLOCKR", "DUNLOCK", "DNOPEN", "DNCLOSE",
    "DNCLOSEALL", "DNEW", "DADD", "DAPPEND", "DTOP", "DGO",
    "DBOTTOM", "DSKIP", "DBLANK", "DDELETE", "DRECALL", "DTAG",
    "DSEEK", "DFBLANK", "DGET", "DPUT", "DFCOPY", "DSELECT",
    "DCHKSTAT", "PCBACCOUNT", "PCBACCSTAT", "DERRMSG",
    "ACCOUNT", "SCANMSGHDR", "CHECKRIP", "RIPVER", "QWKLIMITS",
    "FINDFIRST", "FINDNEXT", "USELMRS", "CONFINFO", "TINKEY",
    "CWD", "INSTRR", "FDORDAKA", "FDORDORG", "FDORDAREA",
    "FDOQRD", "GETDRIVE", "SETDRIVE", "BS2I", "BD2I", "I2BS",
    "I2BD", "FTELL", "OS"
];

#[derive(Debug, PartialEq)]
pub struct StatementDefinition<'a>
{
    pub name: &'a str,
    pub opcode: OpCode,
    pub min_args: i8,
    pub max_args: i8,
}

#[repr(u8)]
#[allow(dead_code)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub enum OpCode {
    WHILE = 0,
    END = 1,
    CLS = 2,
    CLREOL = 3,
    MORE = 4,
    WAIT = 5,
    COLOR = 6,
    GOTO = 7,
    LET = 8,
    PRINT = 9,
    PRINTLN = 10,
    IF = 11,
    CONFFLAG = 12,
    CONFUNFLAG = 13,
    DISPFILE = 14,
    INPUT = 15,
    FCREATE = 16,
    FOPEN = 17,
    FAPPEND = 18,
    FCLOSE = 19,
    FGET = 20,
    FPUT = 21,
    FPUTLN = 22,
    RESETDISP = 23,
    STARTDISP = 24,
    FPUTPAD = 25,
    HANGUP = 26,
    GETUSER = 27,
    PUTUSER = 28,
    DEFCOLOR = 29,
    DELETE = 30,
    DELUSER = 31,
    ADJTIME = 32,
    LOG = 33,
    INPUTSTR = 34,
    INPUTYN = 35,
    INPUTMONEY = 36,
    INPUTINT = 37,
    INPUTCC = 38,
    INPUTDATE = 39,
    INPUTTIME = 40,
    GOSUB = 41,
    RETURN = 42,
    PROMPTSTR = 43,
    DTRON = 44,
    DTROFF = 45,
    CDCHKON = 46,
    CDCHKOFF = 47,
    DELAY = 48,
    SENDMODEM = 49,
    INC = 50,
    DEC = 51,
    NEWLINE = 52,
    NEWLINES = 53,
    TOKENIZE = 54,
    GETTOKEN = 55,
    SHELL = 56,
    DISPTEXT = 57,
    STOP = 58,
    INPUTTEXT = 59,
    BEEP = 60,
    PUSH = 61,
    POP = 62,
    KBDSTUFF = 63,
    CALL = 64,
    JOIN = 65,
    QUEST = 66,
    BLT = 67,
    DIR = 68,
    KBDFILE = 69,
    BYE = 70,
    GOODBYE = 71,
    BROADCAST = 72,
    WAITFOR = 73,
    KBDCHKON = 74,
    KBDCHKOFF = 75,
    OPTEXT = 76,
    DISPSTR = 77,
    RDUNET = 78,
    WRUNET = 79,
    DOINTR = 80,
    VARSEG = 81,
    VAROFF = 82,
    POKEB = 83,
    POKEW = 84,
    VARADDR = 85,
    ANSIPOS = 86,
    BACKUP = 87,
    FORWARD = 88,
    FRESHLINE = 89,
    WRUSYS = 90,
    RDUSYS = 91,
    NEWPWD = 92,
    OPENCAP = 93,
    CLOSECAP = 94,
    MESSAGE = 95,
    SAVESCRN = 96,
    RESTSCRN = 97,
    SOUND = 98,
    CHAT = 99,
    SPRINT = 100,
    SPRINTLN = 101,
    MPRINT = 102,
    MPRINTLN = 103,
    RENAME = 104,
    FREWIND = 105,
    POKEDW = 106,
    DBGLEVEL = 107,
    SHOWON = 108,
    SHOWOFF = 109,
    PAGEON = 110,
    PAGEOFF = 111,
    FSEEK = 112,
    FFLUSH = 113,
    FREAD = 114,
    FWRITE = 115,
    FDEFIN = 116,
    FDEFOUT = 117,
    FDGET = 118,
    FDPUT = 119,
    FDPUTLN = 120,
    FDPUTPAD = 121,
    FDREAD = 122,
    FDWRITE = 123,
    ADJBYTES = 124,
    KBDSTRING = 125,
    ALIAS = 126,
    REDIM = 127,
    APPEND = 128,
    COPY = 129,
    KBDFLUSH = 130,
    MDMFLUSH = 131,
    KEYFLUSH = 132,
    LASTIN = 133,
    FLAG = 134,
    DOWNLOAD = 135,
    WRUSYSDOOR = 136,
    GETALTUSER = 137,
    ADJDBYTES = 138,
    ADJTBYTES = 139,
    ADJTFILES = 140,
    LANG = 141,
    SORT = 142,
    MOUSEREG = 143,
    SCRFILE = 144,
    SEARCHINIT = 145,
    SEARCHFIND = 146,
    SEARCHSTOP = 147,
    PRFOUND = 148,
    PRFOUNDLN = 149,
    TPAGET = 150,
    TPAPUT = 151,
    TPACGET = 152,
    TPACPUT = 153,
    TPAREAD = 154,
    TPAWRITE = 155,
    TPACREAD = 156,
    TPACWRITE = 157,
    BITSET = 158,
    BITCLEAR = 159,
    BRAG = 160,
    FREALTUSER = 161,
    SETLMR = 162,
    SETENV = 163,
    FCLOSEALL = 164,
    DECLARE = 165,
    FUNCTION = 166,
    PROCEDURE = 167,
    PCALL = 168,
    FPCLR = 169,
    BEGIN = 170,
    FEND = 171,
    STATIC = 172,
    STACKABORT = 173,
    DCREATE = 174,
    DOPEN = 175,
    DCLOSE = 176,
    DSETALIAS = 177,
    DPACK = 178,
    DCLOSEALL = 179,
    DLOCK = 180,
    DLOCKR = 181,
    DLOCKG = 182,
    DUNLOCK = 183,
    DNCREATE = 184,
    DNOPEN = 185,
    DNCLOSE = 186,
    DNCLOSEALL = 187,
    DNEW = 188,
    DADD = 189,
    DAPPEND = 190,
    DTOP = 191,
    DGO = 192,
    DBOTTOM = 193,
    DSKIP = 194,
    DBLANK = 195,
    DDELETE = 196,
    DRECALL = 197,
    DTAG = 198,
    DSEEK = 199,
    DFBLANK = 200,
    DGET = 201,
    DPUT = 202,
    DFCOPY = 203,

    EVAL = 204,
    ACCOUNT = 205,
    RECORDUSAGE = 206,
    MSGTOFILE = 207,
    QWKLIMITS = 208,
    COMMAND = 209,
    USELMRS = 210,
    CONFINFO = 211,
    ADJTUBYTES = 212,
    GRAFMODE = 213,
    ADDUSER = 214,
    KILLMSG = 215,
    CHDIR = 216,
    MKDIR = 217,
    REDIR = 218,
    FDOWRAKA = 219,
    FDOADDAKA = 220,
    FDOWRORG = 221,
    FDOADDORG = 222,
    FDOQMOD = 223,
    FDOQADD = 224,
    FDOQDEL = 225,
    SOUNDDELAY = 226,
}

pub static STATEMENT_DEFINITIONS: [StatementDefinition; 212] = [
    // StatementDefinition { name: "END", opcode: OpCode::END, min_args: 0, max_args: 0 },
    StatementDefinition { name: "Cls", opcode: OpCode::CLS, min_args: 0, max_args: 0 },
    StatementDefinition { name: "ClrEOL", opcode: OpCode::CLREOL, min_args: 0, max_args: 0 },
    StatementDefinition { name: "More", opcode: OpCode::MORE, min_args: 0, max_args: 0 },
    StatementDefinition { name: "Wait", opcode: OpCode::WAIT, min_args: 0, max_args: 0 },
    StatementDefinition { name: "Color", opcode: OpCode::COLOR, min_args: 1, max_args: 1 },
    // StatementDefinition { name: "GOTO", opcode: OpCode::GOTO, min_args: 1, max_args: 1 },
    // StatementDefinition { name: "LET", opcode: OpCode::LET, min_args: 2, max_args: 2 },
    StatementDefinition { name: "Print", opcode: OpCode::PRINT, min_args: 1, max_args: 99 },
    StatementDefinition { name: "PrintLn", opcode: OpCode::PRINTLN, min_args: 0, max_args: 99 },
    // StatementDefinition { name: "IF", opcode: OpCode::IF, min_args: 2, max_args: 2 },
    StatementDefinition { name: "ConfFlag", opcode: OpCode::CONFFLAG, min_args: 2, max_args: 2 },
    StatementDefinition { name: "ConfUnflag", opcode: OpCode::CONFUNFLAG, min_args: 2, max_args: 2 },
    StatementDefinition { name: "DispFile", opcode: OpCode::DISPFILE, min_args: 2, max_args: 2 },
    StatementDefinition { name: "Input", opcode: OpCode::INPUT, min_args: 2, max_args: 2 },
    StatementDefinition { name: "FCreate", opcode: OpCode::FCREATE, min_args: 4, max_args: 4 },
    StatementDefinition { name: "FOpen", opcode: OpCode::FOPEN, min_args: 4, max_args: 4 },
    StatementDefinition { name: "FAppend", opcode: OpCode::FAPPEND, min_args: 4, max_args: 4 },
    StatementDefinition { name: "FClose", opcode: OpCode::FCLOSE, min_args: 1, max_args: 1 },
    StatementDefinition { name: "FGet", opcode: OpCode::FGET, min_args: 2, max_args: 2 },
    StatementDefinition { name: "FPut", opcode: OpCode::FPUT, min_args: 2, max_args: 99 },
    StatementDefinition { name: "FPutLn", opcode: OpCode::FPUTLN, min_args: 1, max_args: 99 },
    StatementDefinition { name: "ResetDisp", opcode: OpCode::RESETDISP, min_args: 0, max_args: 0 },
    StatementDefinition { name: "StartDisp", opcode: OpCode::STARTDISP, min_args: 1, max_args: 1 },
    StatementDefinition { name: "FPutPad", opcode: OpCode::FPUTPAD, min_args: 3, max_args: 3 },
    StatementDefinition { name: "Hangup", opcode: OpCode::HANGUP, min_args: 0, max_args: 0 },
    StatementDefinition { name: "GetUser", opcode: OpCode::GETUSER, min_args: 0, max_args: 0 },
    StatementDefinition { name: "PutUser", opcode: OpCode::PUTUSER, min_args: 0, max_args: 0 },
    StatementDefinition { name: "DefColor", opcode: OpCode::DEFCOLOR, min_args: 0, max_args: 0 },
    StatementDefinition { name: "Delete", opcode: OpCode::DELETE, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DelUser", opcode: OpCode::DELUSER, min_args: 0, max_args: 0 },
    StatementDefinition { name: "AdjTime", opcode: OpCode::ADJTIME, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Log", opcode: OpCode::LOG, min_args: 2, max_args: 2 },
    StatementDefinition { name: "InputStr", opcode: OpCode::INPUTSTR, min_args: 6, max_args: 6 },
    StatementDefinition { name: "InputYN", opcode: OpCode::INPUTYN, min_args: 3, max_args: 3 },
    StatementDefinition { name: "InputMoney", opcode: OpCode::INPUTMONEY, min_args: 3, max_args: 3 },
    StatementDefinition { name: "InputInt", opcode: OpCode::INPUTINT, min_args: 3, max_args: 3 },
    StatementDefinition { name: "InputCC", opcode: OpCode::INPUTCC, min_args: 3, max_args: 3 },
    StatementDefinition { name: "InputDate", opcode: OpCode::INPUTDATE, min_args: 3, max_args: 3 },
    StatementDefinition { name: "InputTime", opcode: OpCode::INPUTTIME, min_args: 3, max_args: 3 },
    // StatementDefinition { name: "GOSUB", opcode: OpCode::GOSUB, min_args: 1, max_args: 1 },
    // StatementDefinition { name: "RETURN", opcode: OpCode::RETURN, min_args: 0, max_args: 0 },
    StatementDefinition { name: "PromptStr", opcode: OpCode::PROMPTSTR, min_args: 5, max_args: 5 },
    StatementDefinition { name: "DtrOn", opcode: OpCode::DTRON, min_args: 0, max_args: 0 },
    StatementDefinition { name: "DtrOff", opcode: OpCode::DTROFF, min_args: 0, max_args: 0 },
    StatementDefinition { name: "CdchkOn", opcode: OpCode::CDCHKON, min_args: 0, max_args: 0 },
    StatementDefinition { name: "CdchkOff", opcode: OpCode::CDCHKOFF, min_args: 0, max_args: 0 },
    StatementDefinition { name: "Delay", opcode: OpCode::DELAY, min_args: 1, max_args: 1 },
    StatementDefinition { name: "SendModem", opcode: OpCode::SENDMODEM, min_args: 1, max_args: 1 },
    // StatementDefinition { name: "INC", opcode: OpCode::INC, min_args: 1, max_args: 1 },
    // StatementDefinition { name: "DEC", opcode: OpCode::DEC, min_args: 1, max_args: 1 },
    StatementDefinition { name: "NewLine", opcode: OpCode::NEWLINE, min_args: 0, max_args: 0 },
    StatementDefinition { name: "NewLines", opcode: OpCode::NEWLINES, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Tokenize", opcode: OpCode::TOKENIZE, min_args: 1, max_args: 1 },
    StatementDefinition { name: "GetToken", opcode: OpCode::GETTOKEN, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Shell", opcode: OpCode::SHELL, min_args: 4, max_args: 4 },
    StatementDefinition { name: "DispText", opcode: OpCode::DISPTEXT, min_args: 2, max_args: 2 },
    // StatementDefinition { name: "STOP", opcode: OpCode::STOP, min_args: 0, max_args: 0 },
    StatementDefinition { name: "InputText", opcode: OpCode::INPUTTEXT, min_args: 4, max_args: 4 },
    StatementDefinition { name: "Beep", opcode: OpCode::BEEP, min_args: 0, max_args: 0 },
    StatementDefinition { name: "Push", opcode: OpCode::PUSH, min_args: 1, max_args: 99 },
    StatementDefinition { name: "Pop", opcode: OpCode::POP, min_args: 1, max_args: 99 },
    StatementDefinition { name: "KbdStuff", opcode: OpCode::KBDSTUFF, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Call", opcode: OpCode::CALL, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Join", opcode: OpCode::JOIN, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Quest", opcode: OpCode::QUEST, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Blt", opcode: OpCode::BLT, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Dir", opcode: OpCode::DIR, min_args: 1, max_args: 1 },
    StatementDefinition { name: "KbdFile", opcode: OpCode::KBDFILE, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Bye", opcode: OpCode::BYE, min_args: 0, max_args: 0 },
    StatementDefinition { name: "Goodbye", opcode: OpCode::GOODBYE, min_args: 0, max_args: 0 },
    StatementDefinition { name: "Broadcast", opcode: OpCode::BROADCAST, min_args: 3, max_args: 3 },
    StatementDefinition { name: "WaitFor", opcode: OpCode::WAITFOR, min_args: 3, max_args: 3 },
    StatementDefinition { name: "KbdchkOn", opcode: OpCode::KBDCHKON, min_args: 0, max_args: 0 },
    StatementDefinition { name: "KbdchkOff", opcode: OpCode::KBDCHKOFF, min_args: 0, max_args: 0 },
    StatementDefinition { name: "OpText", opcode: OpCode::OPTEXT, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DispStr", opcode: OpCode::DISPSTR, min_args: 1, max_args: 1 },
    StatementDefinition { name: "RDUnet", opcode: OpCode::RDUNET, min_args: 1, max_args: 1 },
    StatementDefinition { name: "WRUnet", opcode: OpCode::WRUNET, min_args: 6, max_args: 6 },
    StatementDefinition { name: "DoIntr", opcode: OpCode::DOINTR, min_args: 10, max_args: 10 },
    StatementDefinition { name: "VarSeg", opcode: OpCode::VARSEG, min_args: 2, max_args: 2 },
    StatementDefinition { name: "VarOff", opcode: OpCode::VAROFF, min_args: 2, max_args: 2 },
    StatementDefinition { name: "PokeB", opcode: OpCode::POKEB, min_args: 2, max_args: 2 },
    StatementDefinition { name: "PokeW", opcode: OpCode::POKEW, min_args: 2, max_args: 2 },
    StatementDefinition { name: "VarAddr", opcode: OpCode::VARADDR, min_args: 2, max_args: 2 },
    StatementDefinition { name: "AnsiPos", opcode: OpCode::ANSIPOS, min_args: 2, max_args: 2 },
    StatementDefinition { name: "Backup", opcode: OpCode::BACKUP, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Forward", opcode: OpCode::FORWARD, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Freshline", opcode: OpCode::FRESHLINE, min_args: 0, max_args: 0 },
    StatementDefinition { name: "WRUSys", opcode: OpCode::WRUSYS, min_args: 0, max_args: 0 },
    StatementDefinition { name: "RDUSys", opcode: OpCode::RDUSYS, min_args: 0, max_args: 0 },
    StatementDefinition { name: "NewPwd", opcode: OpCode::NEWPWD, min_args: 2, max_args: 2 },
    StatementDefinition { name: "OpenCap", opcode: OpCode::OPENCAP, min_args: 2, max_args: 2 },
    StatementDefinition { name: "CloseCap", opcode: OpCode::CLOSECAP, min_args: 0, max_args: 0 },
    StatementDefinition { name: "Message", opcode: OpCode::MESSAGE, min_args: 9, max_args: 9 },
    StatementDefinition { name: "SaveScrn", opcode: OpCode::SAVESCRN, min_args: 0, max_args: 0 },
    StatementDefinition { name: "RestScrn", opcode: OpCode::RESTSCRN, min_args: 0, max_args: 0 },
    StatementDefinition { name: "Sound", opcode: OpCode::SOUND, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Chat", opcode: OpCode::CHAT, min_args: 0, max_args: 0 },
    StatementDefinition { name: "SPrint", opcode: OpCode::SPRINT, min_args: 1, max_args: 99 },
    StatementDefinition { name: "SPrintLN", opcode: OpCode::SPRINTLN, min_args: 0, max_args: 99 },
    StatementDefinition { name: "MPrint", opcode: OpCode::MPRINT, min_args: 1, max_args: 99 },
    StatementDefinition { name: "MPrintLn", opcode: OpCode::MPRINTLN, min_args: 0, max_args: 99 },
    StatementDefinition { name: "Rename", opcode: OpCode::RENAME, min_args: 2, max_args: 2 },
    StatementDefinition { name: "FRewind", opcode: OpCode::FREWIND, min_args: 1, max_args: 1 },
    StatementDefinition { name: "PokeDW", opcode: OpCode::POKEDW, min_args: 2, max_args: 2 },
    StatementDefinition { name: "DbgLevel", opcode: OpCode::DBGLEVEL, min_args: 1, max_args: 1 },
    StatementDefinition { name: "ShowOn", opcode: OpCode::SHOWON, min_args: 0, max_args: 0 },
    StatementDefinition { name: "ShowOff", opcode: OpCode::SHOWOFF, min_args: 0, max_args: 0 },
    StatementDefinition { name: "PageOn", opcode: OpCode::PAGEON, min_args: 0, max_args: 0 },
    StatementDefinition { name: "PageOFf", opcode: OpCode::PAGEOFF, min_args: 0, max_args: 0 },
    StatementDefinition { name: "FSeek", opcode: OpCode::FSEEK, min_args: 3, max_args: 3 },
    StatementDefinition { name: "FFlush", opcode: OpCode::FFLUSH, min_args: 1, max_args: 1 },
    StatementDefinition { name: "FRead", opcode: OpCode::FREAD, min_args: 3, max_args: 3 },
    StatementDefinition { name: "FWrite", opcode: OpCode::FWRITE, min_args: 3, max_args: 3 },
    StatementDefinition { name: "FDefIn", opcode: OpCode::FDEFIN, min_args: 1, max_args: 1 },
    StatementDefinition { name: "FDefOut", opcode: OpCode::FDEFOUT, min_args: 1, max_args: 1 },
    StatementDefinition { name: "FDGet", opcode: OpCode::FDGET, min_args: 1, max_args: 1 },
    StatementDefinition { name: "FDPut", opcode: OpCode::FDPUT, min_args: 1, max_args: 99 },
    StatementDefinition { name: "FDPutLn", opcode: OpCode::FDPUTLN, min_args: 0, max_args: 99 },
    StatementDefinition { name: "FDPutPad", opcode: OpCode::FDPUTPAD, min_args: 2, max_args: 2 },
    StatementDefinition { name: "FDRead", opcode: OpCode::FDREAD, min_args: 2, max_args: 2 },
    StatementDefinition { name: "FDWrite", opcode: OpCode::FDWRITE, min_args: 0, max_args: 0 },
    StatementDefinition { name: "AdjBytes", opcode: OpCode::ADJBYTES, min_args: 1, max_args: 1 },
    StatementDefinition { name: "KbdString", opcode: OpCode::KBDSTRING, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Alias", opcode: OpCode::ALIAS, min_args: 1, max_args: 1 },
    StatementDefinition { name: "ReDim", opcode: OpCode::REDIM, min_args: 1, max_args: 4 },
    StatementDefinition { name: "Append", opcode: OpCode::APPEND, min_args: 2, max_args: 2 },
    StatementDefinition { name: "Copy", opcode: OpCode::COPY, min_args: 2, max_args: 2 },
    StatementDefinition { name: "KbdFlush", opcode: OpCode::KBDFLUSH, min_args: 0, max_args: 0 },
    StatementDefinition { name: "MdmFlush", opcode: OpCode::MDMFLUSH, min_args: 0, max_args: 0 },
    StatementDefinition { name: "KeyFlush", opcode: OpCode::KEYFLUSH, min_args: 0, max_args: 0 },
    StatementDefinition { name: "LastIn", opcode: OpCode::LASTIN, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Flag", opcode: OpCode::FLAG, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Download", opcode: OpCode::DOWNLOAD, min_args: 1, max_args: 1 },
    StatementDefinition { name: "WRUsysDoor", opcode: OpCode::WRUSYSDOOR, min_args: 1, max_args: 1 },
    StatementDefinition { name: "GetAltUser", opcode: OpCode::GETALTUSER, min_args: 1, max_args: 1 },
    StatementDefinition { name: "AdjDBytes", opcode: OpCode::ADJDBYTES, min_args: 1, max_args: 1 },
    StatementDefinition { name: "AdjTBytes", opcode: OpCode::ADJTBYTES, min_args: 1, max_args: 1 },
    StatementDefinition { name: "AyjTFiles", opcode: OpCode::ADJTFILES, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Lang", opcode: OpCode::LANG, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Sort", opcode: OpCode::SORT, min_args: 2, max_args: 2 },
    StatementDefinition { name: "MouseReg", opcode: OpCode::MOUSEREG, min_args: 10, max_args: 10 },
    StatementDefinition { name: "ScrFile", opcode: OpCode::SCRFILE, min_args: 2, max_args: 2 },
    StatementDefinition { name: "SearchInit", opcode: OpCode::SEARCHINIT, min_args: 2, max_args: 2 },
    StatementDefinition { name: "SearchFind", opcode: OpCode::SEARCHFIND, min_args: 2, max_args: 2 },
    StatementDefinition { name: "SearchStop", opcode: OpCode::SEARCHSTOP, min_args: 0, max_args: 0 },
    StatementDefinition { name: "PrFound", opcode: OpCode::PRFOUND, min_args: 1, max_args: 99 },
    StatementDefinition { name: "PrFoundLn", opcode: OpCode::PRFOUNDLN, min_args: 0, max_args: 99 },
    StatementDefinition { name: "TPAGet", opcode: OpCode::TPAGET, min_args: 2, max_args: 2 },
    StatementDefinition { name: "TPAPut", opcode: OpCode::TPAPUT, min_args: 2, max_args: 2 },
    StatementDefinition { name: "TPACGea", opcode: OpCode::TPACGET, min_args: 3, max_args: 3 },
    StatementDefinition { name: "TPACPut", opcode: OpCode::TPACPUT, min_args: 3, max_args: 3 },
    StatementDefinition { name: "TPARead", opcode: OpCode::TPAREAD, min_args: 2, max_args: 2 },
    StatementDefinition { name: "TPAWrite", opcode: OpCode::TPAWRITE, min_args: 2, max_args: 2 },
    StatementDefinition { name: "TPACRead", opcode: OpCode::TPACREAD, min_args: 3, max_args: 3 },
    StatementDefinition { name: "TPACWrite", opcode: OpCode::TPACWRITE, min_args: 3, max_args: 3 },
    StatementDefinition { name: "BitSet", opcode: OpCode::BITSET, min_args: 2, max_args: 2 },
    StatementDefinition { name: "BitClear", opcode: OpCode::BITCLEAR, min_args: 2, max_args: 2 },
    StatementDefinition { name: "Brag", opcode: OpCode::BRAG, min_args: 0, max_args: 0 },
    StatementDefinition { name: "FRealTUser", opcode: OpCode::FREALTUSER, min_args: 0, max_args: 0 },
    StatementDefinition { name: "SetLMR", opcode: OpCode::SETLMR, min_args: 2, max_args: 2 },
    StatementDefinition { name: "SetEnv", opcode: OpCode::SETENV, min_args: 1, max_args: 1 },
    StatementDefinition { name: "FCloseAll", opcode: OpCode::FCLOSEALL, min_args: 0, max_args: 0 },
    // StatementDefinition { name: "Declare", opcode: OpCode::DECLARE, min_args: 2, max_args: 2 },
    // StatementDefinition { name: "Function", opcode: OpCode::FUNCTION, min_args: 1, max_args: 1 },
    // StatementDefinition { name: "Procedure", opcode: OpCode::PROCEDURE, min_args: 1, max_args: 1 },
    // StatementDefinition { name: "PCALL", opcode: OpCode::PCALL, min_args: -1, max_args: -1 }, // ????
    // StatementDefinition { name: "FPCLR", opcode: OpCode::FPCLR, min_args: 0, max_args: 0 }, // ????
    StatementDefinition { name: "Begin", opcode: OpCode::BEGIN, min_args: 0, max_args: 0 },
   // StatementDefinition { name: "FEND", opcode: OpCode::FEND, min_args: 0, max_args: 0 }, // Both functions and procedures
    StatementDefinition { name: "Static", opcode: OpCode::STATIC, min_args: 0, max_args: 0 },
    StatementDefinition { name: "StackAbort", opcode: OpCode::STACKABORT, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DCreate", opcode: OpCode::DCREATE, min_args: 4, max_args: 4 },
    StatementDefinition { name: "DOpen", opcode: OpCode::DOPEN, min_args: 3, max_args: 3 },
    StatementDefinition { name: "DClose", opcode: OpCode::DCLOSE, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DSetAlias", opcode: OpCode::DSETALIAS, min_args: 2, max_args: 2 },
    StatementDefinition { name: "DPack", opcode: OpCode::DPACK, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DCloseAll", opcode: OpCode::DCLOSEALL, min_args: 0, max_args: 0 },
    StatementDefinition { name: "DLock", opcode: OpCode::DLOCK, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DLockF", opcode: OpCode::DLOCK, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DLockR", opcode: OpCode::DLOCKR, min_args: 2, max_args: 2 },
    StatementDefinition { name: "DLockG", opcode: OpCode::DLOCKG, min_args: 3, max_args: 3 },
    StatementDefinition { name: "DUnlock", opcode: OpCode::DUNLOCK, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DNCreate", opcode: OpCode::DNCREATE, min_args: 3, max_args: 3 },
    StatementDefinition { name: "DNOpen", opcode: OpCode::DNOPEN, min_args: 2, max_args: 2 },
    StatementDefinition { name: "DNClose", opcode: OpCode::DNCLOSE, min_args: 2, max_args: 2 },
    StatementDefinition { name: "DNCloseAll", opcode: OpCode::DNCLOSEALL, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DNew", opcode: OpCode::DNEW, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DAdd", opcode: OpCode::DADD, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DAppend", opcode: OpCode::DAPPEND, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DTop", opcode: OpCode::DTOP, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DGo", opcode: OpCode::DGO, min_args: 2, max_args: 2 },
    StatementDefinition { name: "DBottom", opcode: OpCode::DBOTTOM, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DSkip", opcode: OpCode::DSKIP, min_args: 2, max_args: 2 },
    StatementDefinition { name: "DBlank", opcode: OpCode::DBLANK, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DDelete", opcode: OpCode::DDELETE, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DRecall", opcode: OpCode::DRECALL, min_args: 1, max_args: 1 },
    StatementDefinition { name: "DTag", opcode: OpCode::DTAG, min_args: 2, max_args: 2 },
    StatementDefinition { name: "DSeek", opcode: OpCode::DSEEK, min_args: 2, max_args: 2 },
    StatementDefinition { name: "DFBlank", opcode: OpCode::DFBLANK, min_args: 2, max_args: 2 },
    StatementDefinition { name: "DGet", opcode: OpCode::DGET, min_args: 3, max_args: 3 },
    StatementDefinition { name: "DPut", opcode: OpCode::DPUT, min_args: 3, max_args: 3 },
    StatementDefinition { name: "DFCopy", opcode: OpCode::DFCOPY, min_args: 4, max_args: 4 },
    StatementDefinition { name: "Eval", opcode: OpCode::EVAL, min_args: 1, max_args: 1 },
    StatementDefinition { name: "Account", opcode: OpCode::ACCOUNT, min_args: 2, max_args: 2 },
    StatementDefinition { name: "RecordUsage", opcode: OpCode::RECORDUSAGE, min_args: 5, max_args: 5 },
    StatementDefinition { name: "MsgToFile", opcode: OpCode::MSGTOFILE, min_args: 3, max_args: 3 },
    StatementDefinition { name: "QwkLimits", opcode: OpCode::QWKLIMITS, min_args: 2, max_args: 2 },
    StatementDefinition { name: "Command", opcode: OpCode::COMMAND, min_args: 2, max_args: 2 },
    StatementDefinition { name: "USelMrs", opcode: OpCode::USELMRS, min_args: 1, max_args: 1 },
    StatementDefinition { name: "ConfInfo", opcode: OpCode::CONFINFO, min_args: 3, max_args: 3 },
    StatementDefinition { name: "AdjTUBytes", opcode: OpCode::ADJTUBYTES, min_args: -1, max_args: -1 },
    StatementDefinition { name: "GrafMode", opcode: OpCode::GRAFMODE, min_args: 1, max_args: 1 },
    StatementDefinition { name: "AddUser", opcode: OpCode::ADDUSER, min_args: 2, max_args: 2 },
    StatementDefinition { name: "KillMsg", opcode: OpCode::KILLMSG, min_args: 2, max_args: 2 },
    StatementDefinition { name: "ChDir", opcode: OpCode::CHDIR, min_args: 1, max_args: 1 },
    StatementDefinition { name: "MkDir", opcode: OpCode::MKDIR, min_args: 1, max_args: 1 },
    StatementDefinition { name: "ReDir", opcode: OpCode::REDIR, min_args: 1, max_args: 1 },
    StatementDefinition { name: "FDOWRAka", opcode: OpCode::FDOWRAKA, min_args: 2, max_args: 2 },
    StatementDefinition { name: "FDOADDAka", opcode: OpCode::FDOADDAKA, min_args: 3, max_args: 3 },
    StatementDefinition { name: "FDOWROrg", opcode: OpCode::FDOWRORG, min_args: 2, max_args: 2 },
    StatementDefinition { name: "FDOADDOrg", opcode: OpCode::FDOADDORG, min_args: 3, max_args: 3 },
    StatementDefinition { name: "FDOQMod", opcode: OpCode::FDOQMOD, min_args: 4, max_args: 4 },
    StatementDefinition { name: "FDOQAdd", opcode: OpCode::FDOQADD, min_args: 3, max_args: 3 },
    StatementDefinition { name: "FDOQDel", opcode: OpCode::FDOQDEL, min_args: 1, max_args: 1 },
    StatementDefinition { name: "SoundDelay", opcode: OpCode::SOUNDDELAY, min_args: 2, max_args: 2 }
];



pub const PPL_TRUE : i32 = 1;
pub const PPL_FALSE : i32 = 0;

pub static CONSTANT_VALUES: [(&str, Constant); 57] = [
    ("AUTO", Constant::Integer(0x02000)),
    ("BELL", Constant::Integer(0x00800)),
    ("DEFS", Constant::Integer(0x00)),
    ("ECHODOTS", Constant::Integer(0x00001)),
    ("ERASELINE", Constant::Integer(0x00020)),
    ("FCL", Constant::Integer(0x02)),
    ("FIELDLEN", Constant::Integer(0x00002)),
    ("FNS", Constant::Integer(0x01)),
    ("F_EXP", Constant::Integer(0x02)),
    ("F_MW", Constant::Integer(0x10)),
    ("F_REG", Constant::Integer(0x01)),
    ("F_SEL", Constant::Integer(0x04)),
    ("F_SYS", Constant::Integer(0x04)),
    ("GRAPH", Constant::Integer(0x01)),
    ("GUIDE", Constant::Integer(0x00004)),
    ("HIGHASCII", Constant::Integer(0x01000)),
    ("LANG", Constant::Integer(0x04)),
    ("LFAFTER", Constant::Integer(0x00100)),
    ("LFBEFORE", Constant::Integer(0x00080)),
    ("LOGIT", Constant::Integer(0x08000)),
    ("LOGITLEFT", Constant::Integer(0x10000)),
    ("NC", Constant::Integer(0x00)),
    ("NEWLINE", Constant::Integer(0x00040)),
    ("NOCLEAR", Constant::Integer(0x00400)),
    ("O_RD", Constant::Integer(0x00)),
    ("O_RW", Constant::Integer(0x02)),
    ("O_WR", Constant::Integer(0x01)),
    ("SEC", Constant::Integer(0x02)),
    ("SEEK_CUR", Constant::Integer(0x01)),
    ("SEEK_END", Constant::Integer(0x02)),
    ("SEEK_SET", Constant::Integer(0x00)),
    ("STACKED", Constant::Integer(0x00010)),
    ("S_DB", Constant::Integer(0x03)),
    ("S_DN", Constant::Integer(0x00)),
    ("S_DR", Constant::Integer(0x01)),
    ("S_DW", Constant::Integer(0x02)),
    ("UPCASE", Constant::Integer(0x00008)),
    ("WORDWRAP", Constant::Integer(0x00200)),
    ("YESNO", Constant::Integer(0x04000)),

    // Debug
    ("START_BAL", Constant::Integer(0x00)),
    ("START_SESSION", Constant::Integer(0x01)),
    ("DEB_CALL", Constant::Integer(0x02)),
    ("DEB_TIME", Constant::Integer(0x03)),
    ("DEB_MSGREAD", Constant::Integer(0x04)),
    ("DEB_MSGCAP", Constant::Integer(0x05)),
    ("DEB_MSGWRITE", Constant::Integer(0x06)),
    ("DEB_MSGECHOED", Constant::Integer(0x07)),
    ("DEB_MSGPRIVATE", Constant::Integer(0x08)),
    ("DEB_DOWNFILE", Constant::Integer(0x09)),
    ("DEB_DOWNBYTES", Constant::Integer(0x0A)),
    ("DEB_CHAT", Constant::Integer(0x0B)),
    ("DEB_TPU", Constant::Integer(0x0C)),
    ("DEB_SPECIAL", Constant::Integer(0x0D)),
    ("CRED_UPFILE", Constant::Integer(0x0E)),
    ("CRED_UPBYTES", Constant::Integer(0x0F)),
    ("CRED_SPECIAL", Constant::Integer(0x10)),
    ("SEC_DROP", Constant::Integer(0x11))
];